import type {
  ActionLabel,
  HardConstraint,
  Job,
  OpportunityDecision,
  RoleFamily,
} from "@/lib/domain/types";

export interface SeedOpportunity extends Job {
  companyName: string;
  cityName: string;
  companyTier: "S" | "A" | "B";
  jdSummary: string;
  decision: OpportunityDecision;
}

const CHECKED_AT = "2026-09-21T08:00:00+04:00";
const appleCareers = "https://jobs.apple.com/en-il/search?location=israel-ISR";

function decision(
  score: number,
  action: ActionLabel,
  constraints: HardConstraint[],
  evidence: string[],
  gaps: string[],
): OpportunityDecision {
  return {
    scoreVersion: "2026-08-v1",
    score,
    action,
    constraints,
    sourceConfidence: action === "benchmark" ? 88 : 96,
    explanationCoverage: 95,
    dimensions: [
      { key: "candidateFit", label: "Candidate fit", score: Math.min(96, score), weight: 0.35, jdEvidence: evidence, candidateEvidence: ["Documented ML project", "Time-series portfolio evidence"], gaps },
      { key: "careerUpside", label: "Career upside", score: Math.min(98, score + 8), weight: 0.2, jdEvidence: ["Research-to-production scope"], candidateEvidence: ["Research-to-industry portfolio"], gaps: [] },
      { key: "compensation", label: "Compensation", score: 70, weight: 0.1, jdEvidence: [], candidateEvidence: [], gaps: ["Employer compensation not stated"] },
      { key: "actionability", label: "Actionability", score: action === "apply_now" ? 90 : 72, weight: 0.2, jdEvidence: ["Official source captured"], candidateEvidence: ["Targeted CV draft available"], gaps: constraints.filter((item) => item.result === "verify").map((item) => item.requirement) },
      { key: "personalFactors", label: "Personal factors", score: 82, weight: 0.15, jdEvidence: [], candidateEvidence: ["English-working market preference"], gaps: [] },
    ],
    nextActions: ["Verify all hard constraints", "Select the matching CV narrative", "Contact one relevant team member"],
  };
}

function opportunity(input: {
  id: string;
  companyId: string;
  companyName: string;
  tier: SeedOpportunity["companyTier"];
  title: string;
  roles: RoleFamily[];
  cityId: string;
  cityName: string;
  officialUrl: string;
  careersUrl: string;
  status?: Job["status"];
  sourceKind?: Job["sourceKind"];
  requirements: string[];
  responsibilities: string[];
  constraints: HardConstraint[];
  score: number;
  action: ActionLabel;
  summary: string;
  postedAt?: string;
  requisitionId?: string;
}): SeedOpportunity {
  return {
    id: input.id,
    companyId: input.companyId,
    companyName: input.companyName,
    companyTier: input.tier,
    title: input.title,
    roleFamilies: input.roles,
    cityId: input.cityId,
    cityName: input.cityName,
    officialUrl: input.officialUrl,
    careersUrl: input.careersUrl,
    sourceKind: input.sourceKind ?? "official_ats",
    status: input.status ?? "verified_open",
    workLanguage: "English",
    checkedAt: CHECKED_AT,
    postedAt: input.postedAt,
    requisitionId: input.requisitionId,
    requirements: input.requirements,
    responsibilities: input.responsibilities,
    preferredSkills: input.requirements.slice(0, 4),
    hardConstraints: input.constraints,
    compensation: { kind: "not_stated", currency: null, min: null, max: null },
    jdSummary: input.summary,
    decision: decision(input.score, input.action, input.constraints, input.requirements.slice(0, 3), input.requirements.slice(3, 5)),
  };
}

const israelAccess: HardConstraint[] = [{ kind: "work_authorization", requirement: "Israel work authorization", result: "verify", evidence: "Sponsorship is not stated on the official posting." }];
const australiaAccess: HardConstraint[] = [{ kind: "work_authorization", requirement: "Australia work rights or sponsorship", result: "verify", evidence: "Confirm eligibility with the recruiter before extensive tailoring." }];
const uaeAccess: HardConstraint[] = [{ kind: "work_authorization", requirement: "UAE work permit or employer sponsorship", result: "verify", evidence: "Confirm sponsorship and relocation terms with the employer." }];

export const seedJobs: SeedOpportunity[] = [
  opportunity({ id: "1001-ml-engineer-doha", companyId: "1001-ai", companyName: "1001 AI", tier: "A", title: "Machine Learning Engineer", roles: ["ai_ml_engineer", "applied_scientist"], cityId: "doha", cityName: "Doha", officialUrl: "https://careers.1001.ai/machine-learning-engineer", careersUrl: "https://careers.1001.ai/", requirements: ["Python", "Machine learning", "Applied AI systems", "Production deployment"], responsibilities: ["Build applied AI systems", "Collaborate with product and data teams"], constraints: [{ kind: "work_authorization", requirement: "Qatar work permit or sponsorship", result: "verify", evidence: "Sponsorship is not stated in the official JD." }], score: 86, action: "apply_now", summary: "Applied ML engineering in Doha with strong research-to-production alignment." }),
  opportunity({ id: "xero-senior-applied-scientist", companyId: "xero", companyName: "Xero", tier: "A", title: "Senior Applied Scientist", roles: ["applied_scientist", "data_scientist"], cityId: "sydney", cityName: "Sydney / Melbourne", officialUrl: "https://jobs.ashbyhq.com/xero/ee697792-1e83-46e8-8ca9-f2f5f0aab821/", careersUrl: "https://jobs.ashbyhq.com/xero", status: "closed", requirements: ["Applied science", "Probability and linear algebra", "Python or Scala", "LLM evaluation", "Production deployment"], responsibilities: ["Lead applied research", "Build and monitor intelligent algorithms at scale"], constraints: australiaAccess, score: 82, action: "benchmark", summary: "Archived after the requisition disappeared from Xero's official Ashby job-board API; history retained." }),
  opportunity({ id: "xero-ml-engineering-manager", companyId: "xero", companyName: "Xero", tier: "A", title: "Engineering Manager – ML & AI", roles: ["ai_ml_engineer", "ai_product"], cityId: "sydney", cityName: "Sydney", officialUrl: "https://jobs.ashbyhq.com/xero/8adc7f0c-e098-440a-ac29-273ee16e41eb", careersUrl: "https://jobs.ashbyhq.com/xero", requirements: ["ML engineering leadership", "MLOps", "Cross-functional product delivery", "Production AI infrastructure"], responsibilities: ["Lead ML engineering", "Partner with applied science and product"], constraints: australiaAccess, score: 74, action: "stretch", summary: "The official ATS now lists Sydney as the primary location and uses the updated ML & AI title; a senior leadership benchmark for AI product engineering.", postedAt: "2026-08-20T00:00:00+10:00" }),
  opportunity({ id: "xero-lead-technical-product-manager", companyId: "xero", companyName: "Xero", tier: "A", title: "Lead Technical Product Manager", roles: ["ai_product", "ai_strategy"], cityId: "sydney", cityName: "Sydney", officialUrl: "https://jobs.ashbyhq.com/xero/161b1b7d-a94b-4b08-87eb-8a7c9df849b5", careersUrl: "https://jobs.ashbyhq.com/xero", requisitionId: "161b1b7d-a94b-4b08-87eb-8a7c9df849b5", requirements: ["Technical product leadership", "Marketing-data platform modernization", "Cross-functional communication", "AI capability integration"], responsibilities: ["Modernize marketing data products", "Embed AI into frontline workflows"], constraints: australiaAccess, score: 74, action: "stretch", summary: "Reopened in Xero's official ATS on 15 September; the role connects data-platform modernization, applied-science collaboration and AI-enabled workflows.", postedAt: "2026-09-15T02:56:49.163+00:00" }),
  opportunity({ id: "xero-lead-technical-product-manager-melbourne-33a5", companyId: "xero", companyName: "Xero", tier: "A", title: "Lead Technical Product Manager", roles: ["ai_product", "ai_strategy"], cityId: "melbourne", cityName: "Melbourne", officialUrl: "https://jobs.ashbyhq.com/xero/33a56861-df8e-420c-8346-7fb4ede8073a", careersUrl: "https://jobs.ashbyhq.com/xero", requisitionId: "33a56861-df8e-420c-8346-7fb4ede8073a", requirements: ["Technical product leadership", "Marketing-data platform modernization", "Cross-functional communication", "AI capability integration"], responsibilities: ["Modernize marketing data products", "Embed AI into frontline workflows"], constraints: australiaAccess, score: 74, action: "stretch", summary: "Melbourne requisition for a technical product leader modernizing data products and integrating AI into frontline workflows.", postedAt: "2026-09-15T02:56:20.384+00:00" }),
  opportunity({ id: "xero-lead-technical-product-manager-brisbane-264e", companyId: "xero", companyName: "Xero", tier: "A", title: "Lead Technical Product Manager", roles: ["ai_product", "ai_strategy"], cityId: "brisbane", cityName: "Brisbane", officialUrl: "https://jobs.ashbyhq.com/xero/264eff6c-86f6-4ca3-a8c7-34f083f06515", careersUrl: "https://jobs.ashbyhq.com/xero", requisitionId: "264eff6c-86f6-4ca3-a8c7-34f083f06515", requirements: ["Technical product leadership", "Marketing-data platform modernization", "Cross-functional communication", "AI capability integration"], responsibilities: ["Modernize marketing data products", "Embed AI into frontline workflows"], constraints: australiaAccess, score: 73, action: "stretch", summary: "Brisbane requisition for a technical product leader modernizing data products and integrating AI into frontline workflows.", postedAt: "2026-09-15T02:56:28.215+00:00" }),
  opportunity({ id: "xero-applied-scientist-ai-products-7c3e", companyId: "xero", companyName: "Xero", tier: "A", title: "Senior / Applied Scientist – AI Products", roles: ["applied_scientist", "data_scientist"], cityId: "melbourne", cityName: "Melbourne", officialUrl: "https://jobs.ashbyhq.com/xero/7c3e039c-02ee-4eba-9dc2-d2c19ba21c6a", careersUrl: "https://jobs.ashbyhq.com/xero", requisitionId: "7c3e039c-02ee-4eba-9dc2-d2c19ba21c6a", requirements: ["Applied science", "Probability and linear algebra", "Python or Scala", "LLM evaluation", "Part-time hybrid role"], responsibilities: ["Lead applied research programs", "Deploy and monitor intelligent algorithms at scale"], constraints: [...australiaAccess, { kind: "onsite", requirement: "Part-time hybrid role based in Melbourne", result: "verify", evidence: "The official ATS lists PartTime employment and a Melbourne hybrid location." }], score: 80, action: "network_first", summary: "Official ATS refreshed this applied-science opening on 17 September; it spans NLP, computer vision, LLMs and production deployment, with a part-time arrangement to confirm.", postedAt: "2026-09-17T02:12:38.391+00:00" }),
  opportunity({ id: "xero-senior-ai-builder-03e1", companyId: "xero", companyName: "Xero", tier: "A", title: "Senior Engineer – AI Builder", roles: ["agent_genai_engineer", "ai_ml_engineer", "ai_product"], cityId: "sydney", cityName: "Sydney", officialUrl: "https://jobs.ashbyhq.com/xero/03e1237c-db16-4cd5-8cc8-0a1eef12e36e", careersUrl: "https://jobs.ashbyhq.com/xero", requisitionId: "03e1237c-db16-4cd5-8cc8-0a1eef12e36e", requirements: ["Python or TypeScript", "LLM coding agents", "API and enterprise-system integration", "Product-minded rapid prototyping"], responsibilities: ["Build internal AI workflows and tools", "Automate operating rhythms across product and technology"], constraints: australiaAccess, score: 81, action: "network_first", summary: "New AI-builder opening focused on coding agents, workflow automation, APIs and rapid internal-product delivery.", postedAt: "2026-09-03T04:03:57.807+00:00" }),
  opportunity({ id: "xero-senior-ml-systems-80be", companyId: "xero", companyName: "Xero", tier: "A", title: "Senior Engineer, ML Systems (AI Products)", roles: ["ai_ml_engineer", "agent_genai_engineer"], cityId: "sydney", cityName: "Sydney", officialUrl: "https://jobs.ashbyhq.com/xero/80be1c3c-9f81-413e-9c80-028c2a7e8969", careersUrl: "https://jobs.ashbyhq.com/xero", requisitionId: "80be1c3c-9f81-413e-9c80-028c2a7e8969", requirements: ["Production Python", "Distributed systems and SQL", "LLM product integration", "ML frameworks and orchestration"], responsibilities: ["Design production AI infrastructure", "Move applied-science models safely into products"], constraints: australiaAccess, score: 78, action: "stretch", summary: "The official ATS refreshed this ML-systems opening on 8 September; it joins distributed production engineering with LLM product delivery.", postedAt: "2026-09-08T12:29:14.265+00:00" }),
  opportunity({ id: "xero-senior-ai-agentic-8fed", companyId: "xero", companyName: "Xero", tier: "A", title: "Senior Engineer – AI Agentic", roles: ["agent_genai_engineer", "ai_ml_engineer"], cityId: "melbourne", cityName: "Melbourne", officialUrl: "https://jobs.ashbyhq.com/xero/8fed11a8-5109-4787-8a2a-a75d860703e2", careersUrl: "https://jobs.ashbyhq.com/xero", requisitionId: "8fed11a8-5109-4787-8a2a-a75d860703e2", requirements: ["C# and .NET on AWS", "Python or TypeScript for AI tooling", "Agent skills and remediation agents", "Production monitoring and rollback"], responsibilities: ["Build Xero's internal agent platform", "Ship reusable AI skills with operational safeguards"], constraints: australiaAccess, score: 84, action: "network_first", summary: "New agent-engineering opening spanning an internal skills marketplace, remediation agents and production-grade monitoring and rollback.", postedAt: "2026-09-08T01:11:50.569+00:00" }),
  opportunity({ id: "xero-senior-ai-workflows-melbourne-207b", companyId: "xero", companyName: "Xero", tier: "A", title: "Senior Engineer – AI Workflows", roles: ["agent_genai_engineer", "ai_ml_engineer"], cityId: "melbourne", cityName: "Melbourne", officialUrl: "https://jobs.ashbyhq.com/xero/207b3ed7-594a-4fde-acb9-0d215d18c989", careersUrl: "https://jobs.ashbyhq.com/xero", requisitionId: "207b3ed7-594a-4fde-acb9-0d215d18c989", requirements: ["Claude or Gemini agent workflows", "MCP and RAG", "Python or TypeScript", "Evaluation, monitoring and security"], responsibilities: ["Build enterprise AI workflow integrations", "Deliver auditable production agent systems"], constraints: australiaAccess, score: 86, action: "network_first", summary: "Official Melbourne requisition for MCP-enabled agents, RAG, enterprise integrations and production evaluation and monitoring.", postedAt: "2026-05-06T00:00:00+10:00" }),
  opportunity({ id: "xero-senior-ai-workflows-sydney-3954", companyId: "xero", companyName: "Xero", tier: "A", title: "Senior Engineer – AI Workflows", roles: ["agent_genai_engineer", "ai_ml_engineer"], cityId: "sydney", cityName: "Sydney", officialUrl: "https://jobs.ashbyhq.com/xero/3954a3b2-6f34-4b29-984c-77f5d5ca813e", careersUrl: "https://jobs.ashbyhq.com/xero", requisitionId: "3954a3b2-6f34-4b29-984c-77f5d5ca813e", requirements: ["Claude or Gemini agent workflows", "MCP and RAG", "Python or TypeScript", "Evaluation, monitoring and security"], responsibilities: ["Build enterprise AI workflow integrations", "Deliver auditable production agent systems"], constraints: australiaAccess, score: 86, action: "network_first", summary: "Official Sydney requisition for MCP-enabled agents, RAG, enterprise integrations and production evaluation and monitoring.", postedAt: "2026-05-06T00:00:00+10:00" }),
  opportunity({ id: "xero-head-product-ai-shared-services-b8dd", companyId: "xero", companyName: "Xero", tier: "A", title: "Head of Product – AI Shared Services", roles: ["ai_product", "ai_strategy"], cityId: "melbourne", cityName: "Melbourne", officialUrl: "https://jobs.ashbyhq.com/xero/b8dda96e-f152-49a8-822b-aaa6c178c0db", careersUrl: "https://jobs.ashbyhq.com/xero", requisitionId: "b8dda96e-f152-49a8-822b-aaa6c178c0db", requirements: ["AI product strategy and roadmaps", "Platform adoption and success metrics", "Executive stakeholder leadership", "Shared-services operating model"], responsibilities: ["Set strategy for shared AI capabilities", "Drive measurable adoption across Xero"], constraints: australiaAccess, score: 73, action: "stretch", summary: "Senior AI-product leadership benchmark focused on shared-platform strategy, adoption, metrics and cross-company impact.", postedAt: "2026-08-31T00:00:00+10:00" }),
  opportunity({ id: "apple-ai-ml-chip-design", companyId: "apple-israel", companyName: "Apple", tier: "S", title: "AI/ML Engineer – Chip Design", roles: ["agent_genai_engineer", "ai_ml_engineer"], cityId: "herzliya", cityName: "Herzliya", officialUrl: "https://jobs.apple.com/en-il/details/200668375-0865/ai-ml-engineer-chip-design?team=MLAI", careersUrl: appleCareers, status: "closed", requirements: ["Agentic GenAI", "Foundation models", "Multi-agent workflows", "Five years applied ML", "Production deployment"], responsibilities: ["Build AI agents for chip design", "Take research into production"], constraints: israelAccess, score: 75, action: "benchmark", summary: "Archived after Apple's exact official job route returned a not-found state; the last verified JD is retained as an agentic-AI benchmark.", postedAt: "2026-06-15T00:00:00+03:00" }),
  opportunity({ id: "apple-mlops-engineer", companyId: "apple-israel", companyName: "Apple", tier: "S", title: "MLOps Engineer", roles: ["ai_ml_engineer"], cityId: "herzliya", cityName: "Herzliya", officialUrl: "https://jobs.apple.com/en-il/details/200666044-0865/mlops-engineer?team=MLAI", careersUrl: appleCareers, requirements: ["MLOps", "Distributed GPU training", "Data pipelines", "Low-latency inference"], responsibilities: ["Own the ML lifecycle", "Bridge research and engineering"], constraints: israelAccess, score: 72, action: "stretch", summary: "Production ML infrastructure benchmark for research-to-engineering growth." }),
  opportunity({ id: "apple-interdisciplinary-researcher", companyId: "apple-israel", companyName: "Apple", tier: "S", title: "Interdisciplinary Researcher", roles: ["applied_scientist"], cityId: "herzliya", cityName: "Herzliya", officialUrl: "https://jobs.apple.com/en-il/details/200666013-0865/interdisciplinary-researcher?team=MLAI", careersUrl: appleCareers, status: "closed", requirements: ["Research methods", "Signal analysis", "Cross-disciplinary experimentation"], responsibilities: ["Research weak physical signals", "Translate discoveries into product technology"], constraints: israelAccess, score: 78, action: "benchmark", summary: "Archived after Apple's exact official job route returned a not-found state; the last verified research scope is retained for benchmarking.", postedAt: "2026-05-31T00:00:00+03:00" }),
  opportunity({ id: "apple-audio-ml-engineer", companyId: "apple-israel", companyName: "Apple", tier: "S", title: "Audio Machine Learning Engineer", roles: ["ai_ml_engineer", "applied_scientist"], cityId: "herzliya", cityName: "Herzliya", officialUrl: "https://jobs.apple.com/en-il/details/200665600-0865/audio-machine-learning-engineer?team=MLAI", careersUrl: appleCareers, requirements: ["Machine learning", "Audio or signal data", "Data lifecycle", "Experimentation"], responsibilities: ["Build audio ML models", "Improve data quality and experiments"], constraints: israelAccess, score: 76, action: "stretch", summary: "Audio ML role emphasizing signal data, experimentation and end-to-end data quality." }),
  opportunity({ id: "apple-ml-engineer-speech", companyId: "apple-israel", companyName: "Apple", tier: "S", title: "Machine Learning Engineer – Speech", roles: ["ai_ml_engineer", "applied_scientist"], cityId: "herzliya", cityName: "Herzliya", officialUrl: "https://jobs.apple.com/en-il/details/200665627-0865/machine-learning-engineer-speech?team=MLAI", careersUrl: appleCareers, requirements: ["Speech recognition", "NLP", "Deep learning", "Production ML"], responsibilities: ["Build conversational AI", "Advance speech and language understanding"], constraints: israelAccess, score: 74, action: "stretch", summary: "Speech ML role emphasizing recognition, NLP, deep learning and production delivery." }),
  opportunity({ id: "apple-ml-research-edge", companyId: "apple-israel", companyName: "Apple", tier: "S", title: "Machine Learning Researcher – Edge & Efficient AI", roles: ["applied_scientist", "ai_ml_engineer"], cityId: "herzliya", cityName: "Herzliya", officialUrl: "https://jobs.apple.com/en-il/details/200665634-0865/machine-learning-researcher-edge-efficient-ai?team=MLAI", careersUrl: appleCareers, requirements: ["Deep learning research", "Efficient AI", "Apple silicon deployment", "Full ML lifecycle"], responsibilities: ["Research edge models", "Deploy models on device"], constraints: israelAccess, score: 77, action: "network_first", summary: "Edge AI research role covering efficient models, Apple silicon and on-device deployment." }),
  opportunity({ id: "apple-ml-engineer-vision", companyId: "apple-israel", companyName: "Apple", tier: "S", title: "Machine Learning Engineer – Vision", roles: ["ai_ml_engineer", "applied_scientist"], cityId: "herzliya", cityName: "Herzliya", officialUrl: "https://jobs.apple.com/en-il/details/200665626-0865/machine-learning-engineer-vision?team=MLAI", careersUrl: appleCareers, requirements: ["Computer vision", "Deep learning", "Signal processing", "Edge ML"], responsibilities: ["Model human interaction", "Build multidisciplinary vision systems"], constraints: israelAccess, score: 79, action: "network_first", summary: "Vision ML role combining computer vision, signal processing and edge deployment." }),
  opportunity({ id: "apple-ml-physics-informed", companyId: "apple-israel", companyName: "Apple", tier: "S", title: "ML Research Engineer – Physics-Informed AI", roles: ["applied_scientist", "ai_ml_engineer"], cityId: "herzliya", cityName: "Herzliya", officialUrl: "https://jobs.apple.com/en-il/details/200665614-0865/ml-research-engineer-physics-informed-ai?team=MLAI", careersUrl: appleCareers, requirements: ["Physics-informed neural networks", "Simulation", "Model validation", "Experimental data"], responsibilities: ["Train physics-informed models", "Integrate simulation and measurements"], constraints: israelAccess, score: 78, action: "network_first", summary: "Physics-informed ML role combining simulation, experimental data and model validation." }),
  opportunity({ id: "apple-ml-data-researcher", companyId: "apple-israel", companyName: "Apple", tier: "S", title: "Machine Learning Data Researcher", roles: ["data_scientist", "applied_scientist"], cityId: "herzliya", cityName: "Herzliya", officialUrl: "https://jobs.apple.com/en-us/details/200665429-0865/machine-learning-data-researcher?team=MLAI", careersUrl: appleCareers, requirements: ["Machine learning", "Physical signal data", "Data quality", "Research experimentation"], responsibilities: ["Research ML data", "Build rigorous model-improvement experiments"], constraints: israelAccess, score: 81, action: "network_first", summary: "ML data research role emphasizing physical signals, data quality and rigorous experimentation." }),
  opportunity({ id: "apple-agentic-full-stack-200674773", companyId: "apple-israel", companyName: "Apple", tier: "S", title: "Full Stack Developer – Agentic AI", roles: ["agent_genai_engineer", "ai_ml_engineer"], cityId: "herzliya", cityName: "Herzliya / Haifa", officialUrl: "https://jobs.apple.com/en-il/details/200674773-0865/full-stack-developer-agentic-ai?team=HRDWR", careersUrl: appleCareers, requisitionId: "200674773-0865", requirements: ["Agentic generative AI systems", "Backend product engineering", "LLM agents in Linux toolchains", "End-to-end infrastructure integration"], responsibilities: ["Build agentic AI systems for chip designers", "Own infrastructure and toolchain integrations"], constraints: israelAccess, score: 84, action: "network_first", summary: "Agentic AI product-engineering role for chip-design workflows, with parallel official requisitions in Herzliya and Haifa.", postedAt: "2026-08-03T00:00:00+03:00" }),
  opportunity({ id: "apple-video-restoration-researcher-200671079", companyId: "apple-israel", companyName: "Apple", tier: "S", title: "Computer Vision Researcher – Video Restoration", roles: ["applied_scientist", "ai_ml_engineer"], cityId: "herzliya", cityName: "Herzliya", officialUrl: "https://jobs.apple.com/en-us/details/200671079-0865/computer-vision-researcher-video-restoration?team=MLAI", careersUrl: appleCareers, requisitionId: "200671079-0865", requirements: ["Computer vision research", "Deep-learning video restoration", "Model experimentation", "Research-to-product delivery"], responsibilities: ["Develop video-restoration models", "Translate research advances into Apple products"], constraints: israelAccess, score: 79, action: "network_first", summary: "Applied research opening focused on deep-learning methods for video restoration and product translation.", postedAt: "2026-07-06T00:00:00+03:00" }),
  opportunity({ id: "airnz-senior-data-scientist", companyId: "air-new-zealand", companyName: "Air New Zealand", tier: "A", title: "Senior Data Scientist", roles: ["data_scientist", "ai_ml_engineer"], cityId: "auckland", cityName: "Auckland", officialUrl: "https://careers.airnewzealand.co.nz/job/senior-data-scientist-in-auckland-nz-jid-919", careersUrl: "https://careers.airnewzealand.co.nz/", status: "closed", requirements: ["Data science", "Machine learning", "Business communication", "Production analytics"], responsibilities: ["Build data-science solutions", "Partner with aviation stakeholders"], constraints: [{ kind: "work_authorization", requirement: "New Zealand work rights or sponsorship", result: "verify", evidence: "Confirm the accredited-employer pathway for future openings." }], score: 75, action: "benchmark", summary: "Archived after the exact official Air New Zealand role page returned 404; the last known JD is retained as a benchmark." }),
  opportunity({ id: "vodacom-genai-data-scientist", companyId: "vodacom", companyName: "Vodacom", tier: "A", title: "Data Scientist – GenAI & Agentic AI", roles: ["agent_genai_engineer", "data_scientist"], cityId: "sandton-midrand", cityName: "Midrand", officialUrl: "https://opportunities.vodafone.com/Vodacom/job/Midrand-Data-Scientist/1428439033/", careersUrl: "https://opportunities.vodafone.com/Vodacom/", status: "closed", requirements: ["RAG", "Agentic workflows", "LLMOps", "Python", "Three to five years experience"], responsibilities: ["Build production LLM applications", "Design multi-agent workflows and human approvals"], constraints: [{ kind: "years", requirement: "3–5 years relevant delivery experience", result: "verify", evidence: "Map research and project delivery evidence against the stated years requirement." }], score: 81, action: "benchmark", summary: "Excellent Agent roadmap benchmark; official closing date was 27 Aug 2026." }),
  opportunity({ id: "inception-ai-engineer-2605", companyId: "inception", companyName: "Inception", tier: "S", title: "AI Engineer", roles: ["ai_ml_engineer", "agent_genai_engineer"], cityId: "abu-dhabi", cityName: "Abu Dhabi", officialUrl: "https://careers.g42.ai/inception/global/en/job/OGWOGJGLOBAL2605EXTERNALENGLOBAL/AI-Engineer", careersUrl: "https://careers.g42.ai/inception/global/en", status: "closed", requisitionId: "OGWOGJGLOBAL2605", requirements: ["Original requirements are no longer displayed by the official ATS"], responsibilities: ["Archived AI engineering requisition retained as a market signal"], constraints: [], score: 48, action: "benchmark", summary: "Official Inception requisition observed as filled; original JD is no longer displayed." }),
  opportunity({ id: "g42-associate-ai-engineer-2803", companyId: "g42", companyName: "G42", tier: "S", title: "Associate AI Engineer", roles: ["ai_ml_engineer", "agent_genai_engineer"], cityId: "abu-dhabi", cityName: "Abu Dhabi", officialUrl: "https://careers.g42.ai/global/en/job/OGWOGJGLOBAL2803EXTERNALENGLOBAL/Associate-AI-Engineer", careersUrl: "https://careers.g42.ai/global/en", status: "closed", requisitionId: "OGWOGJGLOBAL2803", requirements: ["Original requirements are no longer displayed by the official ATS"], responsibilities: ["Archived early-career AI engineering requisition retained as a market signal"], constraints: [], score: 52, action: "benchmark", summary: "Official G42 requisition observed as filled; useful evidence that associate-level AI roles have existed locally." }),
  opportunity({ id: "space42-senior-ai-engineer-2733", companyId: "space42", companyName: "Space42", tier: "A", title: "Senior AI Engineer", roles: ["ai_ml_engineer", "applied_scientist"], cityId: "abu-dhabi", cityName: "Abu Dhabi", officialUrl: "https://careers.g42.ai/global/en/job/OGWOGJGLOBAL2733EXTERNALENGLOBAL/Senior-AI-Engineer-Space42", careersUrl: "https://careers.g42.ai/global/en", status: "closed", requisitionId: "OGWOGJGLOBAL2733", requirements: ["Original requirements are no longer displayed by the official ATS"], responsibilities: ["Archived senior AI requisition retained as a role benchmark"], constraints: [], score: 54, action: "benchmark", summary: "Official Space42 requisition observed as filled; preserve it for seniority and skills benchmarking." }),
  opportunity({ id: "aiq-ml-engineer-900", companyId: "aiq", companyName: "AIQ", tier: "A", title: "Engineer – Machine Learning", roles: ["ai_ml_engineer", "data_scientist"], cityId: "abu-dhabi", cityName: "Abu Dhabi", officialUrl: "https://careers.g42.ai/aiq/global/en/job/OGWOGJGLOBAL900EXTERNALENGLOBAL/Engineer-Machine-Learning", careersUrl: "https://careers.g42.ai/aiq/global/en", status: "closed", requisitionId: "OGWOGJGLOBAL900", requirements: ["Original requirements are no longer displayed by the official ATS"], responsibilities: ["Archived industrial ML requisition retained as a market signal"], constraints: [], score: 58, action: "benchmark", summary: "Official AIQ machine-learning requisition observed as filled." }),
  opportunity({ id: "g42-senior-ml-engineer-2468", companyId: "g42", companyName: "G42 / Inception", tier: "S", title: "Senior Engineer – Machine Learning", roles: ["ai_ml_engineer", "applied_scientist"], cityId: "abu-dhabi", cityName: "Abu Dhabi", officialUrl: "https://careers.g42.ai/inception/global/en/job/OGWOGJGLOBAL2468EXTERNALENGLOBAL/Senior-Engineer-Machine-Learning", careersUrl: "https://careers.g42.ai/inception/global/en", status: "closed", requisitionId: "OGWOGJGLOBAL2468", requirements: ["Original requirements are no longer displayed by the official ATS"], responsibilities: ["Archived senior ML requisition retained as a role benchmark"], constraints: [], score: 55, action: "benchmark", summary: "Official Inception ML requisition observed as filled; no open status is implied." }),
  opportunity({ id: "aiq-senior-backend-engineer-3281", companyId: "aiq", companyName: "AIQ", tier: "A", title: "Senior Backend Engineer", roles: ["ai_ml_engineer"], cityId: "abu-dhabi", cityName: "Abu Dhabi", officialUrl: "https://careers.g42.ai/aiq/global/en/job/OGWOGJGLOBAL3281EXTERNALENGLOBAL/Senior-Backend-Engineer", careersUrl: "https://careers.g42.ai/aiq/global/en", status: "closed", requisitionId: "OGWOGJGLOBAL3281", requirements: ["Original requirements are no longer displayed by the official ATS"], responsibilities: ["Archived backend requisition retained as an adjacent production-engineering signal"], constraints: [], score: 43, action: "benchmark", summary: "Official AIQ requisition observed as filled; useful only as an adjacent engineering benchmark." }),
  opportunity({ id: "g42-lead-ml-qa-2580", companyId: "g42", companyName: "G42", tier: "S", title: "Lead Engineer – ML QA", roles: ["ai_ml_engineer", "ai_product"], cityId: "abu-dhabi", cityName: "Abu Dhabi", officialUrl: "https://careers.g42.ai/global/en/job/OGWOGJGLOBAL2580EXTERNALENGLOBAL/Lead-Engineer-ML-QA", careersUrl: "https://careers.g42.ai/global/en", status: "closed", requisitionId: "OGWOGJGLOBAL2580", requirements: ["Original requirements are no longer displayed by the official ATS"], responsibilities: ["Archived ML quality-assurance requisition retained as a production benchmark"], constraints: [], score: 52, action: "benchmark", summary: "Official G42 ML QA lead requisition observed as filled." }),
  opportunity({ id: "analog-senior-engineer-2881", companyId: "g42", companyName: "Analog (G42)", tier: "A", title: "Senior Engineer", roles: ["ai_ml_engineer"], cityId: "abu-dhabi", cityName: "Abu Dhabi", officialUrl: "https://careers.g42.ai/analog/global/en/job/OGWOGJGLOBAL2881EXTERNALENGLOBAL/Senior-Engineer", careersUrl: "https://careers.g42.ai/analog/global/en", status: "closed", requisitionId: "OGWOGJGLOBAL2881", requirements: ["Original requirements are no longer displayed by the official ATS"], responsibilities: ["Archived engineering requisition retained as an ecosystem signal"], constraints: [], score: 41, action: "benchmark", summary: "Official Analog requisition observed as filled; title is broad and requires no further inference." }),
  opportunity({ id: "g42-data-analytics-engineer-2962", companyId: "g42", companyName: "G42", tier: "S", title: "Engineer – Data Analytics and Reporting", roles: ["data_scientist"], cityId: "abu-dhabi", cityName: "Abu Dhabi", officialUrl: "https://careers.g42.ai/global/en/job/OGWOGJGLOBAL2962EXTERNALENGLOBAL/Engineer-Data-Analytics-and-Reporting", careersUrl: "https://careers.g42.ai/global/en", status: "closed", requisitionId: "OGWOGJGLOBAL2962", requirements: ["Original requirements are no longer displayed by the official ATS"], responsibilities: ["Archived analytics requisition retained as a market signal"], constraints: [], score: 49, action: "benchmark", summary: "Official G42 data analytics requisition observed as filled." }),
  opportunity({ id: "g42-data-scientist-3002", companyId: "g42", companyName: "G42", tier: "S", title: "Data Scientist", roles: ["data_scientist", "applied_scientist"], cityId: "abu-dhabi", cityName: "Abu Dhabi", officialUrl: "https://careers.g42.ai/global/en/job/OGWOGJGLOBAL3002EXTERNALENGLOBAL/Data-Scientist", careersUrl: "https://careers.g42.ai/global/en", status: "closed", requisitionId: "OGWOGJGLOBAL3002", requirements: ["Original requirements are no longer displayed by the official ATS"], responsibilities: ["Archived data-science requisition retained as a market signal"], constraints: [], score: 57, action: "benchmark", summary: "Official G42 data scientist requisition observed as filled; history is preserved without implying availability." }),
  opportunity({ id: "g42-lead-applied-scientist-3243", companyId: "inception", companyName: "Inception (G42)", tier: "S", title: "Lead Applied Scientist", roles: ["applied_scientist", "ai_ml_engineer"], cityId: "abu-dhabi", cityName: "Abu Dhabi", officialUrl: "https://careers.g42.ai/inception/global/en/job/OGWOGJGLOBAL3243EXTERNALENGLOBAL/Lead-Applied-Scientist", careersUrl: "https://careers.g42.ai/inception/global/en/search-results?keywords=AI", requisitionId: "OGWOGJGLOBAL3243", requirements: ["Multimodal and foundation-model research", "Generative AI and reasoning", "Research-to-product leadership", "10–12 years of AI experience"], responsibilities: ["Lead applied-research programs", "Translate advanced models into deployed products"], constraints: [...uaeAccess, { kind: "years", requirement: "10–12 years of AI experience with leadership depth", result: "verify", evidence: "The official JD sets a senior experience and leadership bar." }], score: 82, action: "stretch", summary: "High-upside Abu Dhabi research leadership benchmark spanning foundation models, multimodal AI, reasoning and product deployment.", postedAt: "2026-09-20T00:00:00+04:00" }),
  opportunity({ id: "g42-applied-scientist-594", companyId: "inception", companyName: "Inception (G42)", tier: "S", title: "Applied Scientist", roles: ["applied_scientist", "ai_ml_engineer"], cityId: "abu-dhabi", cityName: "Abu Dhabi", officialUrl: "https://careers.g42.ai/inception/global/en/job/OGWOGJGLOBAL594EXTERNALENGLOBAL/Applied-Scientist", careersUrl: "https://careers.g42.ai/inception/global/en/search-results?keywords=AI", requisitionId: "OGWOGJGLOBAL594", requirements: ["MSc or PhD in an AI-related field", "Computer vision, NLP or speech", "Deep learning and generative AI", "Six or more years developing AI algorithms"], responsibilities: ["Develop multimodal AI models", "Build product prototypes and support client delivery"], constraints: [...uaeAccess, { kind: "years", requirement: "6+ years developing AI algorithms", result: "verify", evidence: "The official JD explicitly requires at least six years." }], score: 88, action: "stretch", summary: "Strong Abu Dhabi applied-science match across multimodal AI, generative models, prototypes and client-facing product delivery, with a six-year bar.", postedAt: "2026-09-20T00:00:00+04:00" }),
  opportunity({ id: "g42-senior-applied-scientist-1336", companyId: "inception", companyName: "Inception (G42)", tier: "S", title: "Senior Applied Scientist", roles: ["applied_scientist", "agent_genai_engineer", "ai_ml_engineer"], cityId: "abu-dhabi", cityName: "Abu Dhabi", officialUrl: "https://careers.g42.ai/inception/global/en/job/OGWOGJGLOBAL1336EXTERNALENGLOBAL/Senior-Applied-Scientist", careersUrl: "https://careers.g42.ai/inception/global/en/search-results?keywords=AI", requisitionId: "OGWOGJGLOBAL1336", requirements: ["Agentic AI and orchestration", "MCP and agent-to-agent protocols", "Advanced RAG and information retrieval", "Eight or more years in applied AI"], responsibilities: ["Build enterprise agent systems", "Advance retrieval, evaluation and production integration"], constraints: [...uaeAccess, { kind: "years", requirement: "8+ years in applied AI", result: "verify", evidence: "The official JD sets an eight-year minimum." }], score: 89, action: "stretch", summary: "High-alignment Abu Dhabi agentic-AI role covering MCP, orchestration, advanced RAG and enterprise deployment; the official JD requires eight or more years.", postedAt: "2026-09-20T00:00:00+04:00" }),
  opportunity({ id: "g42-principal-applied-scientist-1226", companyId: "inception", companyName: "Inception (G42)", tier: "S", title: "Principal Applied Scientist", roles: ["applied_scientist", "ai_ml_engineer"], cityId: "abu-dhabi", cityName: "Abu Dhabi", officialUrl: "https://careers.g42.ai/inception/global/en/job/OGWOGJGLOBAL1226EXTERNALENGLOBAL/Principal-Applied-Scientist", careersUrl: "https://careers.g42.ai/inception/global/en/search-results?keywords=AI", requisitionId: "OGWOGJGLOBAL1226", requirements: ["MSc or PhD in an AI-related field", "Computer vision, NLP or speech specialization", "Research or product-driven R&D record", "Ten or more years developing AI algorithms"], responsibilities: ["Set applied-research direction", "Deliver AI innovations and production proofs of concept"], constraints: [...uaeAccess, { kind: "years", requirement: "10+ years developing AI algorithms", result: "verify", evidence: "The official JD explicitly requires a minimum of ten years." }], score: 81, action: "stretch", summary: "Principal-level Abu Dhabi applied-science benchmark with a ten-year bar and emphasis on measurable research-to-product outcomes.", postedAt: "2026-09-20T00:00:00+04:00" }),
  opportunity({ id: "g42-senior-manager-investment-ai-3335", companyId: "inception", companyName: "Inception (G42)", tier: "S", title: "Senior Manager – Investment AI Platform", roles: ["ai_product", "ai_strategy", "quant_financial_ml"], cityId: "abu-dhabi", cityName: "Abu Dhabi", officialUrl: "https://careers.g42.ai/inception/global/en/job/OGWOGJGLOBAL3335EXTERNALENGLOBAL/Senior-Manager-Investment-AI-Platform-Market-Specialist-SME", careersUrl: "https://careers.g42.ai/inception/global/en/search-results?keywords=AI", requisitionId: "OGWOGJGLOBAL3335", requirements: ["Investment lifecycle expertise", "Private markets or sovereign investing", "AI output evaluation and traceability", "Six or more years in investing"], responsibilities: ["Translate investment workflows into product requirements", "Validate AI outputs with design partners across the GCC"], constraints: [...uaeAccess, { kind: "years", requirement: "6+ years in private-market or sovereign investing", result: "verify", evidence: "The official JD explicitly requires relevant investment experience." }], score: 78, action: "stretch", summary: "Rare Abu Dhabi intersection of investment workflows, AI-product requirements and model-output governance; domain seniority is the main constraint.", postedAt: "2026-09-20T00:00:00+04:00" }),
  opportunity({ id: "g42-product-manager-investment-ai-3341", companyId: "inception", companyName: "Inception (G42)", tier: "S", title: "Product Manager – Investment AI", roles: ["ai_product", "ai_strategy", "quant_financial_ml"], cityId: "abu-dhabi", cityName: "Abu Dhabi", officialUrl: "https://careers.g42.ai/inception/global/en/job/OGWOGJGLOBAL3341EXTERNALENGLOBAL/Product-Manager", careersUrl: "https://careers.g42.ai/inception/global/en/search-results?keywords=AI", requisitionId: "OGWOGJGLOBAL3341", requirements: ["Enterprise SaaS product ownership", "Investment-lifecycle workflows", "AI evaluation and grounding", "Eight or more years in product management"], responsibilities: ["Own a cross-module investment-AI roadmap", "Define quality measures, requirements and enterprise controls"], constraints: [...uaeAccess, { kind: "years", requirement: "8+ years in product management", result: "verify", evidence: "The official JD explicitly requires at least eight years." }], score: 86, action: "stretch", summary: "Excellent AI-product case-study target spanning roadmap ownership, investment workflows, AI evaluation, data residency and commercial decisions.", postedAt: "2026-09-20T00:00:00+04:00" }),
  opportunity({ id: "g42-director-product-technology-3334", companyId: "inception", companyName: "Inception (G42)", tier: "S", title: "Director – Product Technology", roles: ["ai_product", "ai_strategy", "agent_genai_engineer"], cityId: "abu-dhabi", cityName: "Abu Dhabi", officialUrl: "https://careers.g42.ai/inception/global/en/job/OGWOGJGLOBAL3334EXTERNALENGLOBAL/Director-Product-Technology", careersUrl: "https://careers.g42.ai/inception/global/en/search-results?keywords=AI", requisitionId: "OGWOGJGLOBAL3334", requirements: ["Agent-platform architecture", "Distributed systems and APIs", "AI evaluation, grounding and safety", "Senior product-engineering leadership"], responsibilities: ["Set the roadmap for a shared agentic-AI platform", "Guide secure enterprise deployment from prototype to scale"], constraints: [...uaeAccess, { kind: "years", requirement: "Senior director-level product-engineering leadership", result: "verify", evidence: "The official JD describes a director-level leadership scope." }], score: 79, action: "stretch", summary: "Director-level benchmark for agent-platform productization, sovereign deployment, observability and AI economics.", postedAt: "2026-09-08T00:00:00+04:00" }),
  opportunity({ id: "g42-senior-manager-solution-engineering-2880", companyId: "inception", companyName: "Inception (G42)", tier: "S", title: "Senior Manager – Solution Engineering", roles: ["ai_strategy", "ai_product", "agent_genai_engineer"], cityId: "abu-dhabi", cityName: "Abu Dhabi", officialUrl: "https://careers.g42.ai/inception/global/en/job/OGWOGJGLOBAL2880EXTERNALENGLOBAL/Senior-Manager-Solution-Engineering", careersUrl: "https://careers.g42.ai/inception/global/en/search-results?keywords=AI", requisitionId: "OGWOGJGLOBAL2880", requirements: ["LLMs, RAG and vector databases", "Agentic and conversational AI", "Technical consulting or solution engineering", "Executive communication and rapid prototyping"], responsibilities: ["Design and de-risk enterprise AI solutions", "Lead discovery, prototypes and executive technical narratives"], constraints: [...uaeAccess, { kind: "years", requirement: "Senior solution-engineering or AI-architecture depth", result: "verify", evidence: "The official JD targets a senior technical authority." }], score: 84, action: "stretch", summary: "Strong AI-strategy and solution-engineering benchmark connecting agentic architectures, prototypes, customer discovery and product feedback.", postedAt: "2026-09-21T00:00:00+04:00" }),
  opportunity({ id: "nvidia-ai-developer-tech-2013673", companyId: "nvidia-israel", companyName: "NVIDIA", tier: "S", title: "Senior AI Developer Technology Engineer", roles: ["ai_ml_engineer", "applied_scientist"], cityId: "tel-aviv", cityName: "Tel Aviv", officialUrl: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/Senior-AI-Developer-Technology-Engineer_JR2013673", careersUrl: "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite?q=Israel", requisitionId: "JR2013673", requirements: ["Deep learning and machine learning", "GPU-accelerated workloads", "Senior engineering depth"], responsibilities: ["Research and develop GPU acceleration techniques for AI workloads"], constraints: israelAccess, score: 72, action: "stretch", summary: "Current NVIDIA role focused on accelerating deep-learning and ML workloads." }),
  opportunity({ id: "nvidia-tensorrt-llm-2008357", companyId: "nvidia-israel", companyName: "NVIDIA", tier: "S", title: "Senior AI Software Development Engineer – TensorRT-LLM", roles: ["agent_genai_engineer", "ai_ml_engineer"], cityId: "haifa", cityName: "Yokneam / Haifa", officialUrl: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/Senior-AI-Software-Development-Engineer--TensorRT-LLM_JR2008357", careersUrl: "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite?q=Israel", status: "closed", requisitionId: "JR2008357", requirements: ["LLM inference", "Deep learning", "High-performance AI software", "Senior systems engineering"], responsibilities: ["Develop TensorRT-LLM inference technology"], constraints: israelAccess, score: 73, action: "benchmark", summary: "Archived after requisition JR2008357 returned no result in NVIDIA's official Workday API; history retained." }),
  opportunity({ id: "nvidia-llm-inference-research-2017780", companyId: "nvidia-israel", companyName: "NVIDIA", tier: "S", title: "Senior Deep Learning Research Engineer – LLM Inference", roles: ["applied_scientist", "agent_genai_engineer"], cityId: "tel-aviv", cityName: "Tel Aviv", officialUrl: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/Israel-Tel-Aviv/Senior-Deep-Learning-Research-Engineer--LLM-Inference_JR2017780", careersUrl: "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite?q=Israel", requisitionId: "JR2017780", requirements: ["Deep learning research", "LLM inference algorithms", "Research engineering", "Senior-level delivery"], responsibilities: ["Develop next-generation LLM inference algorithms"], constraints: israelAccess, score: 77, action: "network_first", summary: "Current NVIDIA research-engineering role directly connected to LLM inference." }),
  opportunity({ id: "nvidia-dl-inference-1985934", companyId: "nvidia-israel", companyName: "NVIDIA", tier: "S", title: "Senior Software Engineer – Deep Learning Inference", roles: ["ai_ml_engineer"], cityId: "tel-aviv", cityName: "Tel Aviv", officialUrl: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/Senior-Software-Engineer--Deep-Learning-Inference_JR1985934", careersUrl: "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite?q=Israel", status: "closed", requisitionId: "JR1985934", requirements: ["Deep learning inference", "Software engineering", "High-performance systems"], responsibilities: ["Engineer deep-learning inference systems"], constraints: israelAccess, score: 69, action: "benchmark", summary: "Archived after requisition JR1985934 returned no result in NVIDIA's official Workday API; history retained." }),
  opportunity({ id: "nvidia-senior-dl-research-2013721", companyId: "nvidia-israel", companyName: "NVIDIA", tier: "S", title: "Senior Deep Learning Research Engineer", roles: ["applied_scientist", "ai_ml_engineer"], cityId: "tel-aviv", cityName: "Tel Aviv", officialUrl: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/Senior-Deep-Learning-Research-Engineer_JR2013721", careersUrl: "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite?q=Israel", status: "closed", requisitionId: "JR2013721", requirements: ["Deep learning research", "Research engineering", "Senior-level impact"], responsibilities: ["Advance deep-learning research and engineering"], constraints: israelAccess, score: 75, action: "benchmark", summary: "Archived after requisition JR2013721 returned no result in NVIDIA's official Workday API; history retained." }),
  opportunity({ id: "nvidia-llm-software-2016753", companyId: "nvidia-israel", companyName: "NVIDIA", tier: "S", title: "Senior Software Engineer – LLM Inference", roles: ["agent_genai_engineer", "ai_ml_engineer"], cityId: "tel-aviv", cityName: "Tel Aviv", officialUrl: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/Israel-Tel-Aviv/Senior-Software-Engineer--Deep-Learning-Inference_JR2016753", careersUrl: "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite?q=Israel", requisitionId: "JR2016753", requirements: ["LLM inference and generative AI", "CUDA or Triton kernels", "Distributed inference", "Five or more years in performance-critical systems"], responsibilities: ["Optimize LLM and omnimodal inference", "Ship production features in vLLM, SGLang and related runtimes"], constraints: [...israelAccess, { kind: "years", requirement: "5+ years of performance-critical software engineering", result: "verify", evidence: "The official NVIDIA requisition explicitly requires five or more years." }], score: 75, action: "stretch", summary: "Newly verified LLM-inference systems role covering MoE, SSMs, quantization, CUDA/Triton and distributed deployment.", postedAt: "2026-07-21T00:00:00+03:00" }),
  opportunity({ id: "nvidia-llm-researcher-2017410", companyId: "nvidia-israel", companyName: "NVIDIA", tier: "S", title: "Senior Deep Learning Researcher – LLM Inference", roles: ["applied_scientist", "agent_genai_engineer"], cityId: "tel-aviv", cityName: "Tel Aviv", officialUrl: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/Senior-Deep-Learning-Researcher--LLM-Inference_JR2017410-1", careersUrl: "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite?q=Israel", requisitionId: "JR2017410", requirements: ["MSc or PhD in a related field", "LLM inference research", "Top-tier AI publications", "Five or more years of relevant research"], responsibilities: ["Invent low-latency and high-throughput LLM algorithms", "Translate research into NVIDIA software"], constraints: [...israelAccess, { kind: "years", requirement: "5+ years of deep-learning or applied research", result: "verify", evidence: "The official NVIDIA requisition explicitly requires at least five years." }], score: 82, action: "network_first", summary: "Newly verified applied-research role focused on LLM inference algorithms, HPC and research-to-product translation.", postedAt: "2026-08-03T00:00:00+03:00" }),
  opportunity({ id: "nvidia-applied-ai-biology-2016711", companyId: "nvidia-israel", companyName: "NVIDIA", tier: "S", title: "Senior Applied AI Researcher – Digital Biology", roles: ["applied_scientist", "agent_genai_engineer", "data_scientist"], cityId: "tel-aviv", cityName: "Tel Aviv / Yokneam", officialUrl: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/Senior-Applied-AI-Researcher--Digital-Biology_JR2016711-1", careersUrl: "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite?q=Israel", requisitionId: "JR2016711", requirements: ["PhD in machine learning or a related field", "Multimodal and clinical time-series learning", "Agentic and generative AI", "Eight or more years of large-scale deep learning"], responsibilities: ["Develop foundation, multimodal and agentic models for biology", "Build digital-twin and clinical AI systems"], constraints: [...israelAccess, { kind: "years", requirement: "8+ years developing and deploying deep-learning models", result: "verify", evidence: "The official NVIDIA requisition explicitly requires eight or more years." }], score: 85, action: "stretch", summary: "Newly verified digital-biology research role spanning transformers, time-series, multimodal learning and agentic AI, with a high seniority bar.", postedAt: "2026-04-24T00:00:00+03:00" }),
  opportunity({ id: "nvidia-diffusion-researcher-2013876", companyId: "nvidia-israel", companyName: "NVIDIA", tier: "S", title: "Senior Deep Learning Researcher – Diffusion", roles: ["applied_scientist", "agent_genai_engineer"], cityId: "tel-aviv", cityName: "Tel Aviv", officialUrl: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/Israel-Tel-Aviv/Senior-Deep-Learning-Researcher--Diffusion_JR2013876", careersUrl: "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite?q=Israel", requisitionId: "JR2013876", requirements: ["PhD or equivalent research experience", "Generative AI and diffusion models", "Image or video understanding and generation", "Top-tier research publications"], responsibilities: ["Advance diffusion and multimodal research", "Translate generative-AI research into enterprise software"], constraints: [...israelAccess, { kind: "years", requirement: "3+ years of relevant research experience", result: "verify", evidence: "The official NVIDIA requisition states a three-year research-experience requirement." }], score: 83, action: "network_first", summary: "New generative-AI research opening spanning diffusion, multimodal reasoning and image and video generation.", postedAt: "2026-08-26T00:00:00+03:00" }),
  opportunity({ id: "nvidia-deep-learning-solutions-2024979", companyId: "nvidia-israel", companyName: "NVIDIA", tier: "S", title: "Senior Solutions Architect – Deep Learning", roles: ["ai_ml_engineer", "ai_strategy", "agent_genai_engineer"], cityId: "tel-aviv", cityName: "Tel Aviv", officialUrl: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/Israel-Tel-Aviv/Senior-Solutions-Architect---Deep-Learning_JR2024979", careersUrl: "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite?q=Israel", requisitionId: "JR2024979", requirements: ["Machine learning and deep-learning architecture", "PyTorch, vLLM or Triton", "GPU, CUDA and MLOps systems", "Customer strategy and technical communication"], responsibilities: ["Design Agentic and Physical AI solutions", "Lead customer architecture, demos and technical strategy"], constraints: [...israelAccess, { kind: "years", requirement: "5+ years in software engineering or data analytics", result: "verify", evidence: "The official NVIDIA requisition explicitly states five or more years." }], score: 77, action: "stretch", summary: "New customer-facing architecture role connecting Agentic AI, accelerated computing, MLOps and technical strategy.", postedAt: "2026-09-14T00:00:00+03:00" }),
  opportunity({ id: "nvidia-agentic-systems-researcher-2016502", companyId: "nvidia-israel", companyName: "NVIDIA", tier: "S", title: "Senior Applied Researcher – AI Agentic Systems", roles: ["applied_scientist", "agent_genai_engineer"], cityId: "tel-aviv", cityName: "Tel Aviv", officialUrl: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/Israel-Tel-Aviv/Senior-Applied-Researcher--AI-Agentic-Systems_JR2016502", careersUrl: "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite?q=Israel", requisitionId: "JR2016502", requirements: ["Multi-agent coordination", "Long-horizon reasoning and planning", "RAG and agent evaluation", "Production Python and agent frameworks"], responsibilities: ["Research enterprise agent systems", "Build evaluation sets, telemetry and production prototypes"], constraints: [...israelAccess, { kind: "years", requirement: "10+ years in applied ML, AI or systems", result: "verify", evidence: "The official NVIDIA requisition has a very senior experience threshold." }], score: 82, action: "stretch", summary: "High-alignment but very senior agentic-systems research role spanning multi-agent planning, RAG, evaluation and telemetry.", postedAt: "2026-04-24T00:00:00+03:00" }),
  opportunity({ id: "nvidia-senior-ai-solutions-engineer-2025034", companyId: "nvidia-israel", companyName: "NVIDIA", tier: "S", title: "Senior AI Solutions Engineer", roles: ["agent_genai_engineer", "ai_ml_engineer", "ai_strategy"], cityId: "haifa", cityName: "Yokneam / Tel Aviv", officialUrl: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/Israel-Yokneam/Senior-AI-Solutions-Engineer_JR2025034", careersUrl: "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite?q=Israel", requisitionId: "JR2025034", requirements: ["Agentic workflows and RAG", "LLM applications and MCP", "Evaluation and production Python", "Eight or more years in software engineering"], responsibilities: ["Build customer AI-agent integrations", "Lead proofs of concept and production adoption"], constraints: [...israelAccess, { kind: "years", requirement: "8+ years in software engineering, including LLM-agent experience", result: "verify", evidence: "The official NVIDIA requisition explicitly requires a senior experience profile." }], score: 85, action: "stretch", summary: "High-alignment customer-facing agentic-AI role spanning RAG, MCP, evaluation, integration and product adoption, with a seniority constraint.", postedAt: "2026-09-20T00:00:00+03:00" }),
  opportunity({ id: "nvidia-senior-ai-systems-engineer-2025271", companyId: "nvidia-israel", companyName: "NVIDIA", tier: "S", title: "Senior AI Systems Engineer", roles: ["agent_genai_engineer", "ai_ml_engineer"], cityId: "haifa", cityName: "Yokneam / Tel Aviv", officialUrl: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/Israel-Yokneam/Senior-AI-Systems-Engineer_JR2025271-1", careersUrl: "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite?q=Israel", requisitionId: "JR2025271", requirements: ["Agentic platforms and orchestration", "RAG and vector databases", "End-to-end evaluation and deployment", "Six or more years in software engineering"], responsibilities: ["Design agentic platforms and workflows", "Own code, data, evaluation and deployment systems"], constraints: [...israelAccess, { kind: "years", requirement: "6+ years in software engineering with LLM-agent experience", result: "verify", evidence: "The official NVIDIA requisition sets a six-year software-engineering minimum." }], score: 86, action: "stretch", summary: "Production agent-platform role covering orchestration, RAG, vector systems and end-to-end evaluation and deployment.", postedAt: "2026-09-20T00:00:00+03:00" }),
  opportunity({ id: "nvidia-ai-infrastructure-engineer-2025844", companyId: "nvidia-israel", companyName: "NVIDIA", tier: "S", title: "Senior Software Engineer – AI Infrastructure", roles: ["ai_ml_engineer", "agent_genai_engineer"], cityId: "tel-aviv", cityName: "Tel Aviv", officialUrl: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/Israel-Tel-Aviv/Senior-Software-Engineer--AI-Infrastructure_JR2025844", careersUrl: "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite?q=Israel", requisitionId: "JR2025844", requirements: ["Python or Go", "Kubernetes and distributed systems", "Model and data services", "Five or more years in software engineering"], responsibilities: ["Build production AI infrastructure", "Operate and benchmark scalable model-serving systems"], constraints: [...israelAccess, { kind: "years", requirement: "5+ years in software engineering", result: "verify", evidence: "The official NVIDIA requisition explicitly requires five or more years." }], score: 78, action: "stretch", summary: "AI-infrastructure role spanning Kubernetes, distributed model services, observability and serving runtimes such as vLLM or SGLang.", postedAt: "2026-09-18T00:00:00+03:00" }),
  opportunity({ id: "adia-quant-research-watch", companyId: "adia", companyName: "ADIA", tier: "S", title: "Quantitative Research opportunities", roles: ["quant_financial_ml"], cityId: "abu-dhabi", cityName: "Abu Dhabi", officialUrl: "https://careers.adia.ae/", careersUrl: "https://careers.adia.ae/", status: "discovery_lead", sourceKind: "official_careers", requirements: ["Statistics", "Time-series", "Machine learning", "Financial research"], responsibilities: ["Monitor official quantitative openings"], constraints: [], score: 79, action: "network_first", summary: "High-priority official careers watch; no specific open JD verified yet." }),
  opportunity({ id: "g42-ai-engineering-watch", companyId: "g42", companyName: "G42", tier: "S", title: "AI Engineering opportunities", roles: ["ai_ml_engineer", "agent_genai_engineer"], cityId: "abu-dhabi", cityName: "Abu Dhabi", officialUrl: "https://careers.g42.ai/", careersUrl: "https://careers.g42.ai/", status: "discovery_lead", sourceKind: "official_careers", requirements: ["AI engineering", "Production deployment", "Cloud systems"], responsibilities: ["Monitor operating-company AI openings"], constraints: [], score: 84, action: "network_first", summary: "Local priority watchlist; verify a specific requisition before applying." }),
  opportunity({ id: "bcgx-ai-strategy-watch", companyId: "bcg-x", companyName: "BCG X", tier: "S", title: "AI / Tech Strategy opportunities", roles: ["ai_strategy", "ai_product"], cityId: "dubai", cityName: "Dubai / Riyadh", officialUrl: "https://careers.bcg.com/global/en/x", careersUrl: "https://careers.bcg.com/global/en/x", status: "discovery_lead", sourceKind: "official_careers", requirements: ["AI strategy", "Product thinking", "Executive communication", "Case problem solving"], responsibilities: ["Monitor regional BCG X openings"], constraints: [], score: 73, action: "network_first", summary: "Current BCG X careers watch; Middle East search results require exact-page verification before any open claim." }),
  opportunity({ id: "aws-singapore-ai-watch", companyId: "amazon-global", companyName: "Amazon / AWS", tier: "S", title: "AI, Applied Science & AWS opportunities", roles: ["ai_ml_engineer", "applied_scientist", "ai_product", "ai_strategy"], cityId: "singapore", cityName: "Singapore", officialUrl: "https://www.amazon.jobs/content/locations/singapore", careersUrl: "https://www.amazon.jobs/content/locations/singapore", status: "discovery_lead", sourceKind: "official_careers", requirements: ["Machine learning", "Applied science", "Cloud AI", "Technical product delivery"], responsibilities: ["Monitor the official Singapore careers market for a specific AI requisition"], constraints: [{ kind: "work_authorization", requirement: "Singapore Employment Pass or existing work rights", result: "verify", evidence: "Verify sponsorship on the specific official JD." }], score: 84, action: "network_first", summary: "Official Singapore market watch; no individual requisition is represented as open." }),
  opportunity({ id: "bytedance-singapore-ai-watch", companyId: "bytedance", companyName: "ByteDance", tier: "S", title: "AI / ML & Applied Research opportunities", roles: ["ai_ml_engineer", "applied_scientist", "agent_genai_engineer", "data_scientist"], cityId: "singapore", cityName: "Singapore", officialUrl: "https://joinbytedance.com/search", careersUrl: "https://joinbytedance.com/search", status: "discovery_lead", sourceKind: "official_careers", requirements: ["Machine learning", "Recommendation systems", "Large-scale experimentation", "Production AI"], responsibilities: ["Monitor official Singapore and global PhD opportunities"], constraints: [{ kind: "work_authorization", requirement: "Singapore work authorization or employer sponsorship", result: "verify", evidence: "Confirm against the selected requisition." }], score: 85, action: "network_first", summary: "Official ByteDance careers watch for Singapore; verify a specific role before applying." }),
  opportunity({ id: "nvidia-shanghai-ai-watch", companyId: "nvidia-global", companyName: "NVIDIA", tier: "S", title: "AI Research & Engineering opportunities", roles: ["ai_ml_engineer", "applied_scientist", "agent_genai_engineer"], cityId: "shanghai", cityName: "Shanghai", officialUrl: "https://jobs.nvidia.com/", careersUrl: "https://jobs.nvidia.com/", status: "discovery_lead", sourceKind: "official_careers", requirements: ["Deep learning", "Accelerated computing", "Research engineering", "Production software"], responsibilities: ["Monitor official Shanghai AI and research-engineering openings"], constraints: [{ kind: "language", requirement: "Verify English and Mandarin expectations", result: "verify", evidence: "Working language depends on the team and requisition." }], score: 82, action: "network_first", summary: "Official NVIDIA careers watch for Shanghai; no specific open JD is inferred." }),
  opportunity({ id: "alibaba-hangzhou-ai-watch", companyId: "alibaba", companyName: "Alibaba Group", tier: "S", title: "AI, Cloud & Foundation Model opportunities", roles: ["ai_ml_engineer", "applied_scientist", "agent_genai_engineer", "data_scientist", "ai_product"], cityId: "hangzhou", cityName: "Hangzhou", officialUrl: "https://home.alibabagroup.com/en-US/careers", careersUrl: "https://home.alibabagroup.com/en-US/careers", status: "discovery_lead", sourceKind: "official_careers", requirements: ["Machine learning", "Cloud AI", "Foundation models", "Commerce systems"], responsibilities: ["Monitor official Alibaba recruiting surfaces for a matching Hangzhou requisition"], constraints: [{ kind: "language", requirement: "Verify English and Mandarin expectations", result: "verify", evidence: "Team language is not implied by the group careers page." }], score: 78, action: "network_first", summary: "Official Alibaba market watch; a specific requisition must be verified before application." }),
  opportunity({ id: "google-london-ai-watch", companyId: "google-global", companyName: "Google", tier: "S", title: "AI / ML & Research opportunities", roles: ["ai_ml_engineer", "applied_scientist", "agent_genai_engineer", "ai_product"], cityId: "london", cityName: "London", officialUrl: "https://www.google.com/about/careers/applications/jobs/results/", careersUrl: "https://www.google.com/about/careers/applications/jobs/results/", status: "discovery_lead", sourceKind: "official_careers", requirements: ["Machine learning", "Research engineering", "Product impact", "Production systems"], responsibilities: ["Monitor official London AI and research openings"], constraints: [{ kind: "work_authorization", requirement: "UK work authorization or Skilled Worker sponsorship", result: "verify", evidence: "Verify sponsorship on the selected official JD." }], score: 84, action: "network_first", summary: "Official Google careers watch for London; no individual requisition is represented as open." }),
];
