import type {
  ActionLabel,
  HardConstraint,
  Job,
  OpportunityDecision,
  RoleFamily,
} from "@/lib/domain/types";

export interface SeedOpportunity extends Job {
  companyName: string;
  cityName: string;
  companyTier: "S" | "A" | "B";
  jdSummary: string;
  decision: OpportunityDecision;
}

const CHECKED_AT = "2026-09-07T08:00:00+04:00";
const appleCareers = "https://jobs.apple.com/en-il/search?location=israel-ISR&team=machine-learning-SFTWR-MCHLN";

function decision(
  score: number,
  action: ActionLabel,
  constraints: HardConstraint[],
  evidence: string[],
  gaps: string[],
): OpportunityDecision {
  return {
    scoreVersion: "2026-08-v1",
    score,
    action,
    constraints,
    sourceConfidence: action === "benchmark" ? 88 : 96,
    explanationCoverage: 95,
    dimensions: [
      { key: "candidateFit", label: "Candidate fit", score: Math.min(96, score), weight: 0.35, jdEvidence: evidence, candidateEvidence: ["Documented ML project", "Time-series portfolio evidence"], gaps },
      { key: "careerUpside", label: "Career upside", score: Math.min(98, score + 8), weight: 0.2, jdEvidence: ["Research-to-production scope"], candidateEvidence: ["Research-to-industry portfolio"], gaps: [] },
      { key: "compensation", label: "Compensation", score: 70, weight: 0.1, jdEvidence: [], candidateEvidence: [], gaps: ["Employer compensation not stated"] },
      { key: "actionability", label: "Actionability", score: action === "apply_now" ? 90 : 72, weight: 0.2, jdEvidence: ["Official source captured"], candidateEvidence: ["Targeted CV draft available"], gaps: constraints.filter((item) => item.result === "verify").map((item) => item.requirement) },
      { key: "personalFactors", label: "Personal factors", score: 82, weight: 0.15, jdEvidence: [], candidateEvidence: ["English-working market preference"], gaps: [] },
    ],
    nextActions: ["Verify all hard constraints", "Select the matching CV narrative", "Contact one relevant team member"],
  };
}

function opportunity(input: {
  id: string;
  companyId: string;
  companyName: string;
  tier: SeedOpportunity["companyTier"];
  title: string;
  roles: RoleFamily[];
  cityId: string;
  cityName: string;
  officialUrl: string;
  careersUrl: string;
  status?: Job["status"];
  sourceKind?: Job["sourceKind"];
  requirements: string[];
  responsibilities: string[];
  constraints: HardConstraint[];
  score: number;
  action: ActionLabel;
  summary: string;
  postedAt?: string;
  requisitionId?: string;
}): SeedOpportunity {
  return {
    id: input.id,
    companyId: input.companyId,
    companyName: input.companyName,
    companyTier: input.tier,
    title: input.title,
    roleFamilies: input.roles,
    cityId: input.cityId,
    cityName: input.cityName,
    officialUrl: input.officialUrl,
    careersUrl: input.careersUrl,
    sourceKind: input.sourceKind ?? "official_ats",
    status: input.status ?? "verified_open",
    workLanguage: "English",
    checkedAt: CHECKED_AT,
    postedAt: input.postedAt,
    requisitionId: input.requisitionId,
    requirements: input.requirements,
    responsibilities: input.responsibilities,
    preferredSkills: input.requirements.slice(0, 4),
    hardConstraints: input.constraints,
    compensation: { kind: "not_stated", currency: null, min: null, max: null },
    jdSummary: input.summary,
    decision: decision(input.score, input.action, input.constraints, input.requirements.slice(0, 3), input.requirements.slice(3, 5)),
  };
}

const israelAccess: HardConstraint[] = [{ kind: "work_authorization", requirement: "Israel work authorization", result: "verify", evidence: "Sponsorship is not stated on the official posting." }];
const australiaAccess: HardConstraint[] = [{ kind: "work_authorization", requirement: "Australia work rights or sponsorship", result: "verify", evidence: "Confirm eligibility with the recruiter before extensive tailoring." }];

export const seedJobs: SeedOpportunity[] = [
  opportunity({ id: "1001-ml-engineer-doha", companyId: "1001-ai", companyName: "1001 AI", tier: "A", title: "Machine Learning Engineer", roles: ["ai_ml_engineer", "applied_scientist"], cityId: "doha", cityName: "Doha", officialUrl: "https://careers.1001.ai/machine-learning-engineer", careersUrl: "https://careers.1001.ai/", requirements: ["Python", "Machine learning", "Applied AI systems", "Production deployment"], responsibilities: ["Build applied AI systems", "Collaborate with product and data teams"], constraints: [{ kind: "work_authorization", requirement: "Qatar work permit or sponsorship", result: "verify", evidence: "Sponsorship is not stated in the official JD." }], score: 86, action: "apply_now", summary: "Applied ML engineering in Doha with strong research-to-production alignment." }),
  opportunity({ id: "xero-senior-applied-scientist", companyId: "xero", companyName: "Xero", tier: "A", title: "Senior Applied Scientist", roles: ["applied_scientist", "data_scientist"], cityId: "sydney", cityName: "Sydney / Melbourne", officialUrl: "https://jobs.ashbyhq.com/xero/ee697792-1e83-46e8-8ca9-f2f5f0aab821/", careersUrl: "https://jobs.ashbyhq.com/xero", status: "closed", requirements: ["Applied science", "Probability and linear algebra", "Python or Scala", "LLM evaluation", "Production deployment"], responsibilities: ["Lead applied research", "Build and monitor intelligent algorithms at scale"], constraints: australiaAccess, score: 82, action: "benchmark", summary: "Archived after the requisition disappeared from Xero's official Ashby job-board API; history retained." }),
  opportunity({ id: "xero-ml-engineering-manager", companyId: "xero", companyName: "Xero", tier: "A", title: "Engineering Manager – Machine Learning (AI Products)", roles: ["ai_ml_engineer", "ai_product"], cityId: "melbourne", cityName: "Melbourne / Sydney / Auckland", officialUrl: "https://jobs.ashbyhq.com/xero/8adc7f0c-e098-440a-ac29-273ee16e41eb", careersUrl: "https://jobs.ashbyhq.com/xero", requirements: ["ML engineering leadership", "MLOps", "Cross-functional product delivery", "Production AI infrastructure"], responsibilities: ["Lead ML engineering", "Partner with applied science and product"], constraints: australiaAccess, score: 74, action: "stretch", summary: "Leadership benchmark for moving from research into AI product engineering." }),
  opportunity({ id: "xero-lead-technical-product-manager", companyId: "xero", companyName: "Xero", tier: "A", title: "Lead Technical Product Manager", roles: ["ai_product", "ai_strategy"], cityId: "sydney", cityName: "Australia / New Zealand", officialUrl: "https://jobs.ashbyhq.com/xero/161b1b7d-a94b-4b08-87eb-8a7c9df849b5", careersUrl: "https://jobs.ashbyhq.com/xero", status: "closed", requirements: ["Technical product leadership", "Data platform modernization", "Executive communication", "AI capability integration"], responsibilities: ["Modernize data capabilities", "Embed AI into frontline workflows"], constraints: australiaAccess, score: 72, action: "benchmark", summary: "Archived after the requisition disappeared from Xero's official Ashby job-board API; history retained." }),
  opportunity({ id: "xero-applied-scientist-ai-products-7c3e", companyId: "xero", companyName: "Xero", tier: "A", title: "Senior / Applied Scientist – AI Products", roles: ["applied_scientist", "data_scientist"], cityId: "melbourne", cityName: "Melbourne", officialUrl: "https://jobs.ashbyhq.com/xero/7c3e039c-02ee-4eba-9dc2-d2c19ba21c6a", careersUrl: "https://jobs.ashbyhq.com/xero", requisitionId: "7c3e039c-02ee-4eba-9dc2-d2c19ba21c6a", requirements: ["Applied science", "Probability and linear algebra", "Python or Scala", "LLM evaluation", "Part-time hybrid role"], responsibilities: ["Lead applied research programs", "Deploy and monitor intelligent algorithms at scale"], constraints: [...australiaAccess, { kind: "onsite", requirement: "Part-time hybrid role based in Melbourne", result: "verify", evidence: "The official ATS lists PartTime employment and a Melbourne hybrid location." }], score: 80, action: "network_first", summary: "Newly verified applied-science opening spanning NLP, computer vision, LLMs and production deployment; part-time arrangement needs early confirmation.", postedAt: "2026-08-24T02:48:04.209+00:00" }),
  opportunity({ id: "xero-senior-ai-builder-03e1", companyId: "xero", companyName: "Xero", tier: "A", title: "Senior Engineer – AI Builder", roles: ["agent_genai_engineer", "ai_ml_engineer", "ai_product"], cityId: "sydney", cityName: "Sydney", officialUrl: "https://jobs.ashbyhq.com/xero/03e1237c-db16-4cd5-8cc8-0a1eef12e36e", careersUrl: "https://jobs.ashbyhq.com/xero", requisitionId: "03e1237c-db16-4cd5-8cc8-0a1eef12e36e", requirements: ["Python or TypeScript", "LLM coding agents", "API and enterprise-system integration", "Product-minded rapid prototyping"], responsibilities: ["Build internal AI workflows and tools", "Automate operating rhythms across product and technology"], constraints: australiaAccess, score: 81, action: "network_first", summary: "New AI-builder opening focused on coding agents, workflow automation, APIs and rapid internal-product delivery.", postedAt: "2026-09-03T04:03:57.807+00:00" }),
  opportunity({ id: "xero-senior-ml-systems-80be", companyId: "xero", companyName: "Xero", tier: "A", title: "Senior Engineer – ML Systems (AI Products)", roles: ["ai_ml_engineer", "agent_genai_engineer"], cityId: "sydney", cityName: "Sydney", officialUrl: "https://jobs.ashbyhq.com/xero/80be1c3c-9f81-413e-9c80-028c2a7e8969", careersUrl: "https://jobs.ashbyhq.com/xero", requisitionId: "80be1c3c-9f81-413e-9c80-028c2a7e8969", requirements: ["Production Python", "Distributed systems and SQL", "LLM product integration", "ML frameworks and orchestration"], responsibilities: ["Design production AI infrastructure", "Move applied-science models safely into products"], constraints: australiaAccess, score: 78, action: "stretch", summary: "Newly verified ML-systems opening joining distributed production engineering with LLM product delivery.", postedAt: "2026-08-03T13:39:05.350+00:00" }),
  opportunity({ id: "apple-ai-ml-chip-design", companyId: "apple-israel", companyName: "Apple", tier: "S", title: "AI/ML Engineer – Chip Design", roles: ["agent_genai_engineer", "ai_ml_engineer"], cityId: "herzliya", cityName: "Herzliya", officialUrl: "https://jobs.apple.com/en-il/details/200668375-0865/ai-ml-engineer-chip-design?team=MLAI", careersUrl: appleCareers, requirements: ["Agentic GenAI", "Foundation models", "Multi-agent workflows", "Five years applied ML", "Production deployment"], responsibilities: ["Build AI agents for chip design", "Take research into production"], constraints: israelAccess, score: 75, action: "network_first", summary: "Agentic engineering role requiring five years of applied ML and verified work authorization.", postedAt: "2026-06-15T00:00:00+03:00" }),
  opportunity({ id: "apple-mlops-engineer", companyId: "apple-israel", companyName: "Apple", tier: "S", title: "MLOps Engineer", roles: ["ai_ml_engineer"], cityId: "herzliya", cityName: "Herzliya", officialUrl: "https://jobs.apple.com/en-il/details/200666044-0865/mlops-engineer?team=MLAI", careersUrl: appleCareers, requirements: ["MLOps", "Distributed GPU training", "Data pipelines", "Low-latency inference"], responsibilities: ["Own the ML lifecycle", "Bridge research and engineering"], constraints: israelAccess, score: 72, action: "stretch", summary: "Production ML infrastructure benchmark for research-to-engineering growth." }),
  opportunity({ id: "apple-interdisciplinary-researcher", companyId: "apple-israel", companyName: "Apple", tier: "S", title: "Interdisciplinary Researcher", roles: ["applied_scientist"], cityId: "herzliya", cityName: "Herzliya", officialUrl: "https://jobs.apple.com/en-il/details/200666013-0865/interdisciplinary-researcher?team=MLAI", careersUrl: appleCareers, requirements: ["Research methods", "Signal analysis", "Cross-disciplinary experimentation"], responsibilities: ["Research weak physical signals", "Translate discoveries into product technology"], constraints: israelAccess, score: 78, action: "network_first", summary: "Interdisciplinary research role spanning weak physical signals and product translation; verify work authorization.", postedAt: "2026-05-31T00:00:00+03:00" }),
  opportunity({ id: "apple-audio-ml-engineer", companyId: "apple-israel", companyName: "Apple", tier: "S", title: "Audio Machine Learning Engineer", roles: ["ai_ml_engineer", "applied_scientist"], cityId: "herzliya", cityName: "Herzliya", officialUrl: "https://jobs.apple.com/en-il/details/200665600-0865/audio-machine-learning-engineer?team=MLAI", careersUrl: appleCareers, requirements: ["Machine learning", "Audio or signal data", "Data lifecycle", "Experimentation"], responsibilities: ["Build audio ML models", "Improve data quality and experiments"], constraints: israelAccess, score: 76, action: "stretch", summary: "Audio ML role emphasizing signal data, experimentation and end-to-end data quality." }),
  opportunity({ id: "apple-ml-engineer-speech", companyId: "apple-israel", companyName: "Apple", tier: "S", title: "Machine Learning Engineer – Speech", roles: ["ai_ml_engineer", "applied_scientist"], cityId: "herzliya", cityName: "Herzliya", officialUrl: "https://jobs.apple.com/en-il/details/200665627-0865/machine-learning-engineer-speech?team=MLAI", careersUrl: appleCareers, requirements: ["Speech recognition", "NLP", "Deep learning", "Production ML"], responsibilities: ["Build conversational AI", "Advance speech and language understanding"], constraints: israelAccess, score: 74, action: "stretch", summary: "Speech ML role emphasizing recognition, NLP, deep learning and production delivery." }),
  opportunity({ id: "apple-ml-research-edge", companyId: "apple-israel", companyName: "Apple", tier: "S", title: "Machine Learning Researcher – Edge & Efficient AI", roles: ["applied_scientist", "ai_ml_engineer"], cityId: "herzliya", cityName: "Herzliya", officialUrl: "https://jobs.apple.com/en-il/details/200665634-0865/machine-learning-researcher-edge-efficient-ai?team=MLAI", careersUrl: appleCareers, requirements: ["Deep learning research", "Efficient AI", "Apple silicon deployment", "Full ML lifecycle"], responsibilities: ["Research edge models", "Deploy models on device"], constraints: israelAccess, score: 77, action: "network_first", summary: "Edge AI research role covering efficient models, Apple silicon and on-device deployment." }),
  opportunity({ id: "apple-ml-engineer-vision", companyId: "apple-israel", companyName: "Apple", tier: "S", title: "Machine Learning Engineer – Vision", roles: ["ai_ml_engineer", "applied_scientist"], cityId: "herzliya", cityName: "Herzliya", officialUrl: "https://jobs.apple.com/en-il/details/200665626-0865/machine-learning-engineer-vision?team=MLAI", careersUrl: appleCareers, requirements: ["Computer vision", "Deep learning", "Signal processing", "Edge ML"], responsibilities: ["Model human interaction", "Build multidisciplinary vision systems"], constraints: israelAccess, score: 79, action: "network_first", summary: "Vision ML role combining computer vision, signal processing and edge deployment." }),
  opportunity({ id: "apple-ml-physics-informed", companyId: "apple-israel", companyName: "Apple", tier: "S", title: "ML Research Engineer – Physics-Informed AI", roles: ["applied_scientist", "ai_ml_engineer"], cityId: "herzliya", cityName: "Herzliya", officialUrl: "https://jobs.apple.com/en-il/details/200665614-0865/ml-research-engineer-physics-informed-ai?team=MLAI", careersUrl: appleCareers, requirements: ["Physics-informed neural networks", "Simulation", "Model validation", "Experimental data"], responsibilities: ["Train physics-informed models", "Integrate simulation and measurements"], constraints: israelAccess, score: 78, action: "network_first", summary: "Physics-informed ML role combining simulation, experimental data and model validation." }),
  opportunity({ id: "apple-ml-data-researcher", companyId: "apple-israel", companyName: "Apple", tier: "S", title: "Machine Learning Data Researcher", roles: ["data_scientist", "applied_scientist"], cityId: "herzliya", cityName: "Herzliya", officialUrl: "https://jobs.apple.com/en-us/details/200665429-0865/machine-learning-data-researcher?team=MLAI", careersUrl: appleCareers, requirements: ["Machine learning", "Physical signal data", "Data quality", "Research experimentation"], responsibilities: ["Research ML data", "Build rigorous model-improvement experiments"], constraints: israelAccess, score: 81, action: "network_first", summary: "ML data research role emphasizing physical signals, data quality and rigorous experimentation." }),
  opportunity({ id: "airnz-senior-data-scientist", companyId: "air-new-zealand", companyName: "Air New Zealand", tier: "A", title: "Senior Data Scientist", roles: ["data_scientist", "ai_ml_engineer"], cityId: "auckland", cityName: "Auckland", officialUrl: "https://careers.airnewzealand.co.nz/job/senior-data-scientist-in-auckland-nz-jid-919", careersUrl: "https://careers.airnewzealand.co.nz/", requirements: ["Data science", "Machine learning", "Business communication", "Production analytics"], responsibilities: ["Build data-science solutions", "Partner with aviation stakeholders"], constraints: [{ kind: "work_authorization", requirement: "New Zealand work rights or sponsorship", result: "verify", evidence: "Confirm the accredited-employer pathway for this opening." }], score: 75, action: "stretch", summary: "English-first operational data-science opportunity with visa uncertainty." }),
  opportunity({ id: "vodacom-genai-data-scientist", companyId: "vodacom", companyName: "Vodacom", tier: "A", title: "Data Scientist – GenAI & Agentic AI", roles: ["agent_genai_engineer", "data_scientist"], cityId: "sandton-midrand", cityName: "Midrand", officialUrl: "https://opportunities.vodafone.com/Vodacom/job/Midrand-Data-Scientist/1428439033/", careersUrl: "https://opportunities.vodafone.com/Vodacom/", status: "closed", requirements: ["RAG", "Agentic workflows", "LLMOps", "Python", "Three to five years experience"], responsibilities: ["Build production LLM applications", "Design multi-agent workflows and human approvals"], constraints: [{ kind: "years", requirement: "3–5 years relevant delivery experience", result: "verify", evidence: "Map research and project delivery evidence against the stated years requirement." }], score: 81, action: "benchmark", summary: "Excellent Agent roadmap benchmark; official closing date was 27 Aug 2026." }),
  opportunity({ id: "inception-ai-engineer-2605", companyId: "inception", companyName: "Inception", tier: "S", title: "AI Engineer", roles: ["ai_ml_engineer", "agent_genai_engineer"], cityId: "abu-dhabi", cityName: "Abu Dhabi", officialUrl: "https://careers.g42.ai/inception/global/en/job/OGWOGJGLOBAL2605EXTERNALENGLOBAL/AI-Engineer", careersUrl: "https://careers.g42.ai/inception/global/en", status: "closed", requisitionId: "OGWOGJGLOBAL2605", requirements: ["Original requirements are no longer displayed by the official ATS"], responsibilities: ["Archived AI engineering requisition retained as a market signal"], constraints: [], score: 48, action: "benchmark", summary: "Official Inception requisition observed as filled; original JD is no longer displayed." }),
  opportunity({ id: "g42-associate-ai-engineer-2803", companyId: "g42", companyName: "G42", tier: "S", title: "Associate AI Engineer", roles: ["ai_ml_engineer", "agent_genai_engineer"], cityId: "abu-dhabi", cityName: "Abu Dhabi", officialUrl: "https://careers.g42.ai/global/en/job/OGWOGJGLOBAL2803EXTERNALENGLOBAL/Associate-AI-Engineer", careersUrl: "https://careers.g42.ai/global/en", status: "closed", requisitionId: "OGWOGJGLOBAL2803", requirements: ["Original requirements are no longer displayed by the official ATS"], responsibilities: ["Archived early-career AI engineering requisition retained as a market signal"], constraints: [], score: 52, action: "benchmark", summary: "Official G42 requisition observed as filled; useful evidence that associate-level AI roles have existed locally." }),
  opportunity({ id: "space42-senior-ai-engineer-2733", companyId: "space42", companyName: "Space42", tier: "A", title: "Senior AI Engineer", roles: ["ai_ml_engineer", "applied_scientist"], cityId: "abu-dhabi", cityName: "Abu Dhabi", officialUrl: "https://careers.g42.ai/global/en/job/OGWOGJGLOBAL2733EXTERNALENGLOBAL/Senior-AI-Engineer-Space42", careersUrl: "https://careers.g42.ai/global/en", status: "closed", requisitionId: "OGWOGJGLOBAL2733", requirements: ["Original requirements are no longer displayed by the official ATS"], responsibilities: ["Archived senior AI requisition retained as a role benchmark"], constraints: [], score: 54, action: "benchmark", summary: "Official Space42 requisition observed as filled; preserve it for seniority and skills benchmarking." }),
  opportunity({ id: "aiq-ml-engineer-900", companyId: "aiq", companyName: "AIQ", tier: "A", title: "Engineer – Machine Learning", roles: ["ai_ml_engineer", "data_scientist"], cityId: "abu-dhabi", cityName: "Abu Dhabi", officialUrl: "https://careers.g42.ai/aiq/global/en/job/OGWOGJGLOBAL900EXTERNALENGLOBAL/Engineer-Machine-Learning", careersUrl: "https://careers.g42.ai/aiq/global/en", status: "closed", requisitionId: "OGWOGJGLOBAL900", requirements: ["Original requirements are no longer displayed by the official ATS"], responsibilities: ["Archived industrial ML requisition retained as a market signal"], constraints: [], score: 58, action: "benchmark", summary: "Official AIQ machine-learning requisition observed as filled." }),
  opportunity({ id: "g42-senior-ml-engineer-2468", companyId: "g42", companyName: "G42 / Inception", tier: "S", title: "Senior Engineer – Machine Learning", roles: ["ai_ml_engineer", "applied_scientist"], cityId: "abu-dhabi", cityName: "Abu Dhabi", officialUrl: "https://careers.g42.ai/inception/global/en/job/OGWOGJGLOBAL2468EXTERNALENGLOBAL/Senior-Engineer-Machine-Learning", careersUrl: "https://careers.g42.ai/inception/global/en", status: "closed", requisitionId: "OGWOGJGLOBAL2468", requirements: ["Original requirements are no longer displayed by the official ATS"], responsibilities: ["Archived senior ML requisition retained as a role benchmark"], constraints: [], score: 55, action: "benchmark", summary: "Official Inception ML requisition observed as filled; no open status is implied." }),
  opportunity({ id: "aiq-senior-backend-engineer-3281", companyId: "aiq", companyName: "AIQ", tier: "A", title: "Senior Backend Engineer", roles: ["ai_ml_engineer"], cityId: "abu-dhabi", cityName: "Abu Dhabi", officialUrl: "https://careers.g42.ai/aiq/global/en/job/OGWOGJGLOBAL3281EXTERNALENGLOBAL/Senior-Backend-Engineer", careersUrl: "https://careers.g42.ai/aiq/global/en", status: "closed", requisitionId: "OGWOGJGLOBAL3281", requirements: ["Original requirements are no longer displayed by the official ATS"], responsibilities: ["Archived backend requisition retained as an adjacent production-engineering signal"], constraints: [], score: 43, action: "benchmark", summary: "Official AIQ requisition observed as filled; useful only as an adjacent engineering benchmark." }),
  opportunity({ id: "g42-lead-ml-qa-2580", companyId: "g42", companyName: "G42", tier: "S", title: "Lead Engineer – ML QA", roles: ["ai_ml_engineer", "ai_product"], cityId: "abu-dhabi", cityName: "Abu Dhabi", officialUrl: "https://careers.g42.ai/global/en/job/OGWOGJGLOBAL2580EXTERNALENGLOBAL/Lead-Engineer-ML-QA", careersUrl: "https://careers.g42.ai/global/en", status: "closed", requisitionId: "OGWOGJGLOBAL2580", requirements: ["Original requirements are no longer displayed by the official ATS"], responsibilities: ["Archived ML quality-assurance requisition retained as a production benchmark"], constraints: [], score: 52, action: "benchmark", summary: "Official G42 ML QA lead requisition observed as filled." }),
  opportunity({ id: "analog-senior-engineer-2881", companyId: "g42", companyName: "Analog (G42)", tier: "A", title: "Senior Engineer", roles: ["ai_ml_engineer"], cityId: "abu-dhabi", cityName: "Abu Dhabi", officialUrl: "https://careers.g42.ai/analog/global/en/job/OGWOGJGLOBAL2881EXTERNALENGLOBAL/Senior-Engineer", careersUrl: "https://careers.g42.ai/analog/global/en", status: "closed", requisitionId: "OGWOGJGLOBAL2881", requirements: ["Original requirements are no longer displayed by the official ATS"], responsibilities: ["Archived engineering requisition retained as an ecosystem signal"], constraints: [], score: 41, action: "benchmark", summary: "Official Analog requisition observed as filled; title is broad and requires no further inference." }),
  opportunity({ id: "g42-data-analytics-engineer-2962", companyId: "g42", companyName: "G42", tier: "S", title: "Engineer – Data Analytics and Reporting", roles: ["data_scientist"], cityId: "abu-dhabi", cityName: "Abu Dhabi", officialUrl: "https://careers.g42.ai/global/en/job/OGWOGJGLOBAL2962EXTERNALENGLOBAL/Engineer-Data-Analytics-and-Reporting", careersUrl: "https://careers.g42.ai/global/en", status: "closed", requisitionId: "OGWOGJGLOBAL2962", requirements: ["Original requirements are no longer displayed by the official ATS"], responsibilities: ["Archived analytics requisition retained as a market signal"], constraints: [], score: 49, action: "benchmark", summary: "Official G42 data analytics requisition observed as filled." }),
  opportunity({ id: "g42-data-scientist-3002", companyId: "g42", companyName: "G42", tier: "S", title: "Data Scientist", roles: ["data_scientist", "applied_scientist"], cityId: "abu-dhabi", cityName: "Abu Dhabi", officialUrl: "https://careers.g42.ai/global/en/job/OGWOGJGLOBAL3002EXTERNALENGLOBAL/Data-Scientist", careersUrl: "https://careers.g42.ai/global/en", status: "closed", requisitionId: "OGWOGJGLOBAL3002", requirements: ["Original requirements are no longer displayed by the official ATS"], responsibilities: ["Archived data-science requisition retained as a market signal"], constraints: [], score: 57, action: "benchmark", summary: "Official G42 data scientist requisition observed as filled; history is preserved without implying availability." }),
  opportunity({ id: "nvidia-ai-developer-tech-2013673", companyId: "nvidia-israel", companyName: "NVIDIA", tier: "S", title: "Senior AI Developer Technology Engineer", roles: ["ai_ml_engineer", "applied_scientist"], cityId: "tel-aviv", cityName: "Tel Aviv", officialUrl: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/Senior-AI-Developer-Technology-Engineer_JR2013673", careersUrl: "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite?q=Israel", requisitionId: "JR2013673", requirements: ["Deep learning and machine learning", "GPU-accelerated workloads", "Senior engineering depth"], responsibilities: ["Research and develop GPU acceleration techniques for AI workloads"], constraints: israelAccess, score: 72, action: "stretch", summary: "Current NVIDIA role focused on accelerating deep-learning and ML workloads." }),
  opportunity({ id: "nvidia-tensorrt-llm-2008357", companyId: "nvidia-israel", companyName: "NVIDIA", tier: "S", title: "Senior AI Software Development Engineer – TensorRT-LLM", roles: ["agent_genai_engineer", "ai_ml_engineer"], cityId: "haifa", cityName: "Yokneam / Haifa", officialUrl: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/Senior-AI-Software-Development-Engineer--TensorRT-LLM_JR2008357", careersUrl: "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite?q=Israel", status: "closed", requisitionId: "JR2008357", requirements: ["LLM inference", "Deep learning", "High-performance AI software", "Senior systems engineering"], responsibilities: ["Develop TensorRT-LLM inference technology"], constraints: israelAccess, score: 73, action: "benchmark", summary: "Archived after requisition JR2008357 returned no result in NVIDIA's official Workday API; history retained." }),
  opportunity({ id: "nvidia-llm-inference-research-2017780", companyId: "nvidia-israel", companyName: "NVIDIA", tier: "S", title: "Senior Deep Learning Research Engineer – LLM Inference", roles: ["applied_scientist", "agent_genai_engineer"], cityId: "tel-aviv", cityName: "Tel Aviv", officialUrl: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/Israel-Tel-Aviv/Senior-Deep-Learning-Research-Engineer--LLM-Inference_JR2017780", careersUrl: "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite?q=Israel", requisitionId: "JR2017780", requirements: ["Deep learning research", "LLM inference algorithms", "Research engineering", "Senior-level delivery"], responsibilities: ["Develop next-generation LLM inference algorithms"], constraints: israelAccess, score: 77, action: "network_first", summary: "Current NVIDIA research-engineering role directly connected to LLM inference." }),
  opportunity({ id: "nvidia-dl-inference-1985934", companyId: "nvidia-israel", companyName: "NVIDIA", tier: "S", title: "Senior Software Engineer – Deep Learning Inference", roles: ["ai_ml_engineer"], cityId: "tel-aviv", cityName: "Tel Aviv", officialUrl: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/Senior-Software-Engineer--Deep-Learning-Inference_JR1985934", careersUrl: "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite?q=Israel", status: "closed", requisitionId: "JR1985934", requirements: ["Deep learning inference", "Software engineering", "High-performance systems"], responsibilities: ["Engineer deep-learning inference systems"], constraints: israelAccess, score: 69, action: "benchmark", summary: "Archived after requisition JR1985934 returned no result in NVIDIA's official Workday API; history retained." }),
  opportunity({ id: "nvidia-senior-dl-research-2013721", companyId: "nvidia-israel", companyName: "NVIDIA", tier: "S", title: "Senior Deep Learning Research Engineer", roles: ["applied_scientist", "ai_ml_engineer"], cityId: "tel-aviv", cityName: "Tel Aviv", officialUrl: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/Senior-Deep-Learning-Research-Engineer_JR2013721", careersUrl: "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite?q=Israel", status: "closed", requisitionId: "JR2013721", requirements: ["Deep learning research", "Research engineering", "Senior-level impact"], responsibilities: ["Advance deep-learning research and engineering"], constraints: israelAccess, score: 75, action: "benchmark", summary: "Archived after requisition JR2013721 returned no result in NVIDIA's official Workday API; history retained." }),
  opportunity({ id: "nvidia-llm-software-2016753", companyId: "nvidia-israel", companyName: "NVIDIA", tier: "S", title: "Senior Software Engineer – LLM Inference", roles: ["agent_genai_engineer", "ai_ml_engineer"], cityId: "tel-aviv", cityName: "Tel Aviv", officialUrl: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/Israel-Tel-Aviv/Senior-Software-Engineer--Deep-Learning-Inference_JR2016753", careersUrl: "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite?q=Israel", requisitionId: "JR2016753", requirements: ["LLM inference and generative AI", "CUDA or Triton kernels", "Distributed inference", "Five or more years in performance-critical systems"], responsibilities: ["Optimize LLM and omnimodal inference", "Ship production features in vLLM, SGLang and related runtimes"], constraints: [...israelAccess, { kind: "years", requirement: "5+ years of performance-critical software engineering", result: "verify", evidence: "The official NVIDIA requisition explicitly requires five or more years." }], score: 75, action: "stretch", summary: "Newly verified LLM-inference systems role covering MoE, SSMs, quantization, CUDA/Triton and distributed deployment.", postedAt: "2026-07-21T00:00:00+03:00" }),
  opportunity({ id: "nvidia-llm-researcher-2017410", companyId: "nvidia-israel", companyName: "NVIDIA", tier: "S", title: "Senior Deep Learning Researcher – LLM Inference", roles: ["applied_scientist", "agent_genai_engineer"], cityId: "tel-aviv", cityName: "Tel Aviv", officialUrl: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/Senior-Deep-Learning-Researcher--LLM-Inference_JR2017410-1", careersUrl: "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite?q=Israel", requisitionId: "JR2017410", requirements: ["MSc or PhD in a related field", "LLM inference research", "Top-tier AI publications", "Five or more years of relevant research"], responsibilities: ["Invent low-latency and high-throughput LLM algorithms", "Translate research into NVIDIA software"], constraints: [...israelAccess, { kind: "years", requirement: "5+ years of deep-learning or applied research", result: "verify", evidence: "The official NVIDIA requisition explicitly requires at least five years." }], score: 82, action: "network_first", summary: "Newly verified applied-research role focused on LLM inference algorithms, HPC and research-to-product translation.", postedAt: "2026-08-03T00:00:00+03:00" }),
  opportunity({ id: "nvidia-applied-ai-biology-2016711", companyId: "nvidia-israel", companyName: "NVIDIA", tier: "S", title: "Senior Applied AI Researcher – Digital Biology", roles: ["applied_scientist", "agent_genai_engineer", "data_scientist"], cityId: "tel-aviv", cityName: "Tel Aviv / Yokneam", officialUrl: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/Senior-Applied-AI-Researcher--Digital-Biology_JR2016711-1", careersUrl: "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite?q=Israel", requisitionId: "JR2016711", requirements: ["PhD in machine learning or a related field", "Multimodal and clinical time-series learning", "Agentic and generative AI", "Eight or more years of large-scale deep learning"], responsibilities: ["Develop foundation, multimodal and agentic models for biology", "Build digital-twin and clinical AI systems"], constraints: [...israelAccess, { kind: "years", requirement: "8+ years developing and deploying deep-learning models", result: "verify", evidence: "The official NVIDIA requisition explicitly requires eight or more years." }], score: 85, action: "stretch", summary: "Newly verified digital-biology research role spanning transformers, time-series, multimodal learning and agentic AI, with a high seniority bar.", postedAt: "2026-04-24T00:00:00+03:00" }),
  opportunity({ id: "adia-quant-research-watch", companyId: "adia", companyName: "ADIA", tier: "S", title: "Quantitative Research opportunities", roles: ["quant_financial_ml"], cityId: "abu-dhabi", cityName: "Abu Dhabi", officialUrl: "https://careers.adia.ae/", careersUrl: "https://careers.adia.ae/", status: "discovery_lead", sourceKind: "official_careers", requirements: ["Statistics", "Time-series", "Machine learning", "Financial research"], responsibilities: ["Monitor official quantitative openings"], constraints: [], score: 79, action: "network_first", summary: "High-priority official careers watch; no specific open JD verified yet." }),
  opportunity({ id: "g42-ai-engineering-watch", companyId: "g42", companyName: "G42", tier: "S", title: "AI Engineering opportunities", roles: ["ai_ml_engineer", "agent_genai_engineer"], cityId: "abu-dhabi", cityName: "Abu Dhabi", officialUrl: "https://careers.g42.ai/", careersUrl: "https://careers.g42.ai/", status: "discovery_lead", sourceKind: "official_careers", requirements: ["AI engineering", "Production deployment", "Cloud systems"], responsibilities: ["Monitor operating-company AI openings"], constraints: [], score: 84, action: "network_first", summary: "Local priority watchlist; verify a specific requisition before applying." }),
  opportunity({ id: "bcgx-ai-strategy-watch", companyId: "bcg-x", companyName: "BCG X", tier: "S", title: "AI / Tech Strategy opportunities", roles: ["ai_strategy", "ai_product"], cityId: "dubai", cityName: "Dubai / Riyadh", officialUrl: "https://careers.bcg.com/global/en/teams/bcg-x", careersUrl: "https://careers.bcg.com/global/en/teams/bcg-x", status: "discovery_lead", sourceKind: "official_careers", requirements: ["AI strategy", "Product thinking", "Executive communication", "Case problem solving"], responsibilities: ["Monitor regional BCG X openings"], constraints: [], score: 73, action: "network_first", summary: "Strategy track benchmark; a regional requisition is not yet verified." }),
  opportunity({ id: "aws-singapore-ai-watch", companyId: "amazon-global", companyName: "Amazon / AWS", tier: "S", title: "AI, Applied Science & AWS opportunities", roles: ["ai_ml_engineer", "applied_scientist", "ai_product", "ai_strategy"], cityId: "singapore", cityName: "Singapore", officialUrl: "https://www.amazon.jobs/content/locations/singapore", careersUrl: "https://www.amazon.jobs/content/locations/singapore", status: "discovery_lead", sourceKind: "official_careers", requirements: ["Machine learning", "Applied science", "Cloud AI", "Technical product delivery"], responsibilities: ["Monitor the official Singapore careers market for a specific AI requisition"], constraints: [{ kind: "work_authorization", requirement: "Singapore Employment Pass or existing work rights", result: "verify", evidence: "Verify sponsorship on the specific official JD." }], score: 84, action: "network_first", summary: "Official Singapore market watch; no individual requisition is represented as open." }),
  opportunity({ id: "bytedance-singapore-ai-watch", companyId: "bytedance", companyName: "ByteDance", tier: "S", title: "AI / ML & Applied Research opportunities", roles: ["ai_ml_engineer", "applied_scientist", "agent_genai_engineer", "data_scientist"], cityId: "singapore", cityName: "Singapore", officialUrl: "https://joinbytedance.com/search", careersUrl: "https://joinbytedance.com/search", status: "discovery_lead", sourceKind: "official_careers", requirements: ["Machine learning", "Recommendation systems", "Large-scale experimentation", "Production AI"], responsibilities: ["Monitor official Singapore and global PhD opportunities"], constraints: [{ kind: "work_authorization", requirement: "Singapore work authorization or employer sponsorship", result: "verify", evidence: "Confirm against the selected requisition." }], score: 85, action: "network_first", summary: "Official ByteDance careers watch for Singapore; verify a specific role before applying." }),
  opportunity({ id: "nvidia-shanghai-ai-watch", companyId: "nvidia-global", companyName: "NVIDIA", tier: "S", title: "AI Research & Engineering opportunities", roles: ["ai_ml_engineer", "applied_scientist", "agent_genai_engineer"], cityId: "shanghai", cityName: "Shanghai", officialUrl: "https://jobs.nvidia.com/", careersUrl: "https://jobs.nvidia.com/", status: "discovery_lead", sourceKind: "official_careers", requirements: ["Deep learning", "Accelerated computing", "Research engineering", "Production software"], responsibilities: ["Monitor official Shanghai AI and research-engineering openings"], constraints: [{ kind: "language", requirement: "Verify English and Mandarin expectations", result: "verify", evidence: "Working language depends on the team and requisition." }], score: 82, action: "network_first", summary: "Official NVIDIA careers watch for Shanghai; no specific open JD is inferred." }),
  opportunity({ id: "alibaba-hangzhou-ai-watch", companyId: "alibaba", companyName: "Alibaba Group", tier: "S", title: "AI, Cloud & Foundation Model opportunities", roles: ["ai_ml_engineer", "applied_scientist", "agent_genai_engineer", "data_scientist", "ai_product"], cityId: "hangzhou", cityName: "Hangzhou", officialUrl: "https://home.alibabagroup.com/en-US/careers", careersUrl: "https://home.alibabagroup.com/en-US/careers", status: "discovery_lead", sourceKind: "official_careers", requirements: ["Machine learning", "Cloud AI", "Foundation models", "Commerce systems"], responsibilities: ["Monitor official Alibaba recruiting surfaces for a matching Hangzhou requisition"], constraints: [{ kind: "language", requirement: "Verify English and Mandarin expectations", result: "verify", evidence: "Team language is not implied by the group careers page." }], score: 78, action: "network_first", summary: "Official Alibaba market watch; a specific requisition must be verified before application." }),
  opportunity({ id: "google-london-ai-watch", companyId: "google-global", companyName: "Google", tier: "S", title: "AI / ML & Research opportunities", roles: ["ai_ml_engineer", "applied_scientist", "agent_genai_engineer", "ai_product"], cityId: "london", cityName: "London", officialUrl: "https://www.google.com/about/careers/applications/jobs/results/", careersUrl: "https://www.google.com/about/careers/applications/jobs/results/", status: "discovery_lead", sourceKind: "official_careers", requirements: ["Machine learning", "Research engineering", "Product impact", "Production systems"], responsibilities: ["Monitor official London AI and research openings"], constraints: [{ kind: "work_authorization", requirement: "UK work authorization or Skilled Worker sponsorship", result: "verify", evidence: "Verify sponsorship on the selected official JD." }], score: 84, action: "network_first", summary: "Official Google careers watch for London; no individual requisition is represented as open." }),
];
